import { useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useNavigate, useSearchParams } from 'react-router-dom'
import toast from 'react-hot-toast'
import { Bell, BarChart3, Clock3, Copy, Headphones, MessageSquareText, PhoneCall, Trash2, UserPlus, Users } from 'lucide-react'
import { operationsApi } from '@/api/operationsApi'
import { Card } from '@/components/common/Card'
import { Button } from '@/components/common/Button'
import { Loading } from '@/components/common/Loading'
import { ErrorState } from '@/components/common/ErrorState'
import { Badge } from '@/components/common/Badge'
import { useCurrentUser } from '@/store/authStore'
import { AssignModal } from '@/components/modals/AssignModal'
import { assigneesApi } from '@/api/assigneesApi'

const tabs = [
  ['work', 'My Assigned Cases', Headphones], ['unassigned', 'Cases to Assign', UserPlus], ['sla', 'Response Deadlines', Clock3],
  ['notifications', 'Alerts', Bell], ['contacts', 'Calls & Follow-ups', PhoneCall], ['replies', 'Reply Templates', MessageSquareText],
  ['workload', 'Team Workload', Users], ['analytics', 'Team Reports', BarChart3],
] as const
const routeFor = (type: string, id: number) => type.includes('complaint') ? `/complaints/${id}` : type.includes('ticket') ? `/tickets/${id}` : type.includes('refund') ? `/refunds/${id}` : type.includes('safety') ? `/safety-reports/${id}` : type === 'contact_log' ? `/operations?tab=contacts&follow_up=${id}` : undefined
const SIMPLE_LABELS: Record<string, string> = {
  complaint: 'Customer complaint',
  ticket: 'Help request',
  refund: 'Refund request',
  refundrequest: 'Refund request',
  safetyreport: 'Safety issue',
  safety_report: 'Safety issue',
  under_review: 'Being checked',
  awaiting_info: 'Waiting for information',
  waiting_for_user: 'Waiting for requester',
  in_progress: 'Work in progress',
  action_taken: 'Action completed',
  escalated: 'Sent to senior team',
  submitted: 'New',
}
const label = (value: string) => SIMPLE_LABELS[value] || value?.replace(/_/g, ' ') || '—'
const priorityLabel = (value: string) => ({ critical: 'Critical priority', urgent: 'Urgent priority', high: 'High priority', medium: 'Normal priority', low: 'Low priority', default: 'Normal priority' }[value] || `${label(value)} priority`)
const statusLabel = (value: string) => ({ open: 'Open — work pending', submitted: 'New — not reviewed', in_progress: 'Work in progress', under_review: 'Being checked', awaiting_info: 'Waiting for information', waiting_for_user: 'Waiting for customer reply', resolved: 'Resolved', closed: 'Closed', escalated: 'Sent to senior team' }[value] || label(value))

export const OperationsPage = () => {
  const [searchParams, setSearchParams] = useSearchParams()
  const requestedTab = searchParams.get('tab') as (typeof tabs)[number][0] | null
  const [tab, setTabState] = useState<(typeof tabs)[number][0]>(tabs.some(([key]) => key === requestedTab) ? requestedTab! : 'work')
  const setTab = (value: (typeof tabs)[number][0]) => { setTabState(value); setSearchParams(value === 'work' ? {} : { tab: value }) }
  useEffect(() => { if (requestedTab && tabs.some(([key]) => key === requestedTab)) setTabState(requestedTab) }, [requestedTab])
  const [contact, setContact] = useState({ entity_type: 'complaint', object_id: '', channel: 'call', outcome: 'contacted', note: '', follow_up_at: '' })
  const [reply, setReply] = useState({ title: '', body: '', category: '', visibility: 'shared' })
  const [replySearch, setReplySearch] = useState('')
  const [caseToAssign, setCaseToAssign] = useState<any | null>(null)
  const user = useCurrentUser()
  const navigate = useNavigate()
  const qc = useQueryClient()
  const query = useQuery({ queryKey: ['operations'], queryFn: operationsApi.getOverview, refetchInterval: 30_000 })
  const health = useQuery({ queryKey: ['support-runtime-health'], queryFn: operationsApi.getRuntimeHealth, refetchInterval: 30_000, retry: 1 })
  const refresh = () => qc.invalidateQueries({ queryKey: ['operations'] })
  const readAll = useMutation({ mutationFn: operationsApi.markAllRead, onSuccess: refresh })
  const addContact = useMutation({ mutationFn: operationsApi.addContact, onSuccess: () => { refresh(); toast.success('Follow-up recorded'); setContact({ ...contact, object_id: '', note: '', follow_up_at: '' }) }, onError: () => toast.error('Could not record follow-up') })
  const addReply = useMutation({ mutationFn: operationsApi.addSavedReply, onSuccess: () => { refresh(); toast.success('Saved reply created'); setReply({ title: '', body: '', category: '', visibility: 'shared' }) }, onError: () => toast.error('Could not create saved reply') })
  const assigneesQuery = useQuery({
    queryKey: ['assignees', caseToAssign?.city_id],
    queryFn: () => assigneesApi.getAll(caseToAssign?.city_id ? 'CITY' : 'GLOBAL', caseToAssign?.city_id),
    enabled: !!caseToAssign,
    staleTime: 60_000,
  })

  if (query.isLoading) return <Loading />
  if (query.error || !query.data) return <ErrorState title="Work and reports are unavailable" />
  const data = query.data
  const visibleTabs = user?.role === 'agent' ? tabs.filter(([key]) => key !== 'workload') : tabs
  const filteredReplies = (data.saved_replies || []).filter((item: any) => `${item.title} ${item.category} ${item.body}`.toLowerCase().includes(replySearch.toLowerCase()))
  const downloadReport = () => {
    const rows = [
      ['Metric', 'Value'], ['Open complaints', data.analytics.complaints.open], ['Total complaints', data.analytics.complaints.total],
      ['Open tickets', data.analytics.tickets.open], ['Total tickets', data.analytics.tickets.total],
      ['Pending refunds', data.analytics.refunds.pending], ['Total refunds', data.analytics.refunds.total],
      ['Open safety reports', data.analytics.safety_reports.open], ['Total safety reports', data.analytics.safety_reports.total],
      ['Active staff', data.analytics.staff.active], ['Unread notifications', data.analytics.notifications.unread],
    ]
    const blob = new Blob([rows.map(row => row.join(',')).join('\n')], { type: 'text/csv' })
    const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `support-report-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url)
  }
  return <div className="space-y-5">
    <div><h1 className="text-2xl font-bold text-slate-950">My Work & Reports</h1><p className="mt-1 text-sm text-slate-500">See your assigned cases, response deadlines, follow-ups, ready replies and team reports.</p></div>
    <div className={`flex flex-wrap items-center gap-3 rounded-xl border px-4 py-3 text-sm ${health.data?.healthy ? 'border-emerald-200 bg-emerald-50 text-emerald-900' : 'border-amber-200 bg-amber-50 text-amber-900'}`}><span className={`h-2.5 w-2.5 rounded-full ${health.data?.healthy ? 'bg-emerald-500' : 'bg-amber-500'}`} /><strong>{health.data?.healthy ? 'Support automation is running' : 'Support automation needs attention'}</strong><span>{health.data ? `Redis: ${health.data.redis.ok ? 'connected' : 'disconnected'} · Reminders and SLA worker: ${health.data.automation.ok ? 'running' : 'heartbeat missing'}` : 'Checking Redis and reminder services…'}</span></div>
    <div className="flex gap-1 overflow-x-auto rounded-xl border border-slate-200 bg-white p-1.5 shadow-sm">{visibleTabs.map(([key, title, Icon]) => <button key={key} onClick={() => setTab(key)} className={`flex items-center gap-2 whitespace-nowrap rounded-lg px-3 py-2 text-sm font-medium ${tab === key ? 'bg-slate-900 text-white' : 'text-slate-600 hover:bg-slate-50'}`}><Icon className="h-4 w-4" />{title}</button>)}</div>

    {tab === 'work' && <Card title="Cases assigned to me" subtitle="Open a case to reply, investigate it, or update its status"><div className="divide-y divide-slate-100">{data.my_work.length ? data.my_work.map((item: any) => <button key={`${item.type}-${item.id}`} onClick={() => { const route = routeFor(item.type, item.id); if (route) navigate(route) }} className="w-full py-4 text-left hover:bg-slate-50"><div className="flex flex-wrap items-start gap-3"><div className="min-w-0 flex-1"><p className="truncate font-semibold text-slate-900">{item.title}</p><p className="mt-0.5 text-xs text-slate-500">Case: {label(item.type)} #{item.id} · Received {new Date(item.created_at).toLocaleString()}</p><p className="mt-2 text-sm font-medium text-primary-700"><span className="text-slate-600">What to do next:</span> {item.next_action}</p></div><DeadlineBadge deadline={item.deadline} /></div><div className="mt-3 flex flex-wrap gap-2"><Badge>{priorityLabel(item.priority)}</Badge><Badge>{statusLabel(item.status)}</Badge></div></button>) : <Empty text="No open cases are assigned to you." />}</div></Card>}

    {tab === 'unassigned' && <Card title="Cases waiting for staff" subtitle="Assign urgent and overdue cases first"><div className="divide-y divide-slate-100">{data.unassigned?.length ? data.unassigned.map((item: any) => <div key={`${item.type}-${item.id}`} className="flex flex-wrap items-center gap-3 py-3"><button className="min-w-0 flex-1 text-left" onClick={() => { const route = routeFor(item.type, item.id); if (route) navigate(route) }}><p className="truncate font-medium text-slate-900">{item.title}</p><p className="text-xs text-slate-500">{label(item.type)} #{item.id}{item.city_name ? ` · ${item.city_name}` : ''}</p></button><DeadlineBadge deadline={item.deadline} /><Badge>{label(item.priority)}</Badge>{user?.role === 'agent' ? <Button size="sm" onClick={async () => { await operationsApi.assignToMe(item.type, item.id); await refresh(); toast.success('Case assigned to you') }}>Assign to me</Button> : <Button size="sm" onClick={() => setCaseToAssign(item)}>Assign staff</Button>}</div>) : <Empty text="Every open case has an assigned staff member." />}</div></Card>}

    {tab === 'sla' && <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(data.sla.breaches).map(([key, value]) => <Card key={key}><p className="text-xs font-semibold uppercase text-slate-500">{label(key)}</p><div className="mt-2 flex items-end gap-4"><div><p className={`text-3xl font-bold ${Number(data.sla.first_response_breaches[key]) ? 'text-red-600' : 'text-emerald-600'}`}>{String(data.sla.first_response_breaches[key] || 0)}</p><p className="text-xs text-slate-500">late first replies</p></div><div><p className={`text-3xl font-bold ${Number(value) ? 'text-red-600' : 'text-emerald-600'}`}>{String(value)}</p><p className="text-xs text-slate-500">late resolutions</p></div></div></Card>)}</div>{user?.role === 'admin' ? <SlaSettings onChanged={refresh} /> : <Card title="Response and resolution time limits" subtitle="Only an administrator can change these rules"><SlaReadOnly policies={data.sla.policies} /></Card>}</div>}

    {tab === 'notifications' && <Card title="Case alerts" actions={<Button size="sm" variant="secondary" onClick={() => readAll.mutate()}>Mark all read</Button>}><div className="divide-y">{data.notifications.length ? data.notifications.map((n: any) => <button key={n.id} onClick={async () => { await operationsApi.markRead(n.id); refresh(); const route = routeFor(n.entity_type, Number(n.entity_id)); if (route) navigate(route) }} className={`w-full py-3 text-left ${n.is_read ? 'opacity-60' : ''}`}><p className="font-medium text-slate-900">{n.title}</p><p className="text-sm text-slate-600">{n.message}</p><p className="mt-1 text-xs text-slate-400">{new Date(n.created_at).toLocaleString()}</p></button>) : <Empty text="No new alerts." />}</div></Card>}

    {tab === 'contacts' && <div className="grid gap-5 lg:grid-cols-2"><Card title="Add a call or follow-up"><div className="space-y-3"><Field label="Case type"><select value={contact.entity_type} onChange={e => setContact({ ...contact, entity_type: e.target.value })} className="input"><option value="complaint">Complaint</option><option value="ticket">Support ticket</option><option value="refund">Refund</option><option value="safety_report">Safety report</option></select></Field><Field label="Case ID"><input value={contact.object_id} onChange={e => setContact({ ...contact, object_id: e.target.value })} className="input" type="number" /></Field><div className="grid grid-cols-2 gap-3"><Field label="Contact method"><select value={contact.channel} onChange={e => setContact({ ...contact, channel: e.target.value })} className="input"><option value="call">Call</option><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option><option value="email">Email</option></select></Field><Field label="What happened"><select value={contact.outcome} onChange={e => setContact({ ...contact, outcome: e.target.value })} className="input"><option value="contacted">Contacted</option><option value="no_answer">No answer</option><option value="callback">Callback requested</option><option value="message_sent">Message sent</option><option value="resolved">Resolved</option></select></Field></div><Field label="Contact again on"><input type="datetime-local" value={contact.follow_up_at} onChange={e => setContact({ ...contact, follow_up_at: e.target.value })} className="input" /></Field><Field label="Note"><textarea value={contact.note} onChange={e => setContact({ ...contact, note: e.target.value })} className="input" rows={3} /></Field><Button disabled={!contact.object_id} loading={addContact.isPending} onClick={() => addContact.mutate({ ...contact, object_id: Number(contact.object_id), follow_up_at: contact.follow_up_at || null })}>Save follow-up</Button></div></Card><Card title="Follow-ups I need to do"><div className="divide-y">{data.follow_ups?.length ? data.follow_ups.map((item: any) => <FollowUpItem key={item.id} item={item} onChanged={refresh} />) : <Empty text="No follow-ups are waiting." />}</div></Card></div>}

    {tab === 'replies' && <div className="grid gap-5 lg:grid-cols-[1fr_2fr]">{user?.role !== 'agent' && <Card title="Create a ready reply"><div className="space-y-3"><Field label="Title"><input className="input" value={reply.title} onChange={e => setReply({ ...reply, title: e.target.value })} /></Field><Field label="Category"><input className="input" value={reply.category} onChange={e => setReply({ ...reply, category: e.target.value })} /></Field><Field label="Who can see it"><select className="input" value={reply.visibility} onChange={e => setReply({ ...reply, visibility: e.target.value })}><option value="shared">User and store</option><option value="user">User</option><option value="store">Store</option><option value="internal">Support team only</option></select></Field><Field label="Reply"><textarea className="input" rows={5} value={reply.body} onChange={e => setReply({ ...reply, body: e.target.value })} /></Field><Button disabled={!reply.title || !reply.body} onClick={() => addReply.mutate(reply)}>Create a ready reply</Button></div></Card>}<Card title="Ready replies you can use"><input value={replySearch} onChange={event => setReplySearch(event.target.value)} placeholder="Search ready replies…" className="mb-4 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm" /><div className="grid gap-3">{filteredReplies.length ? filteredReplies.map((item: any) => <SavedReplyItem key={item.id} item={item} canManage={user?.role !== 'agent'} onChanged={refresh} />) : <Empty text="No ready replies have been created yet." />}</div></Card></div>}

    {tab === 'workload' && <Card title="Current team workload" subtitle="Staff with fewer active cases appear first"><div className="divide-y divide-slate-100">{data.workload?.length ? data.workload.map((member: any) => <div key={member.id} className="flex items-center gap-3 py-3"><div className="min-w-0 flex-1"><p className="font-medium text-slate-900">{member.name}</p><p className="text-xs capitalize text-slate-500">{label(member.role)} · {member.is_online ? 'Online now' : member.last_seen_at ? `Last active ${new Date(member.last_seen_at).toLocaleString()}` : 'Not recently active'}</p></div><Badge>{member.active_cases} active cases</Badge></div>) : <Empty text="No active support staff found." />}</div></Card>}

    {tab === 'analytics' && <div className="space-y-4"><div className="flex justify-end"><Button variant="secondary" onClick={downloadReport}>Download report</Button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric title="Open complaints" value={data.analytics.complaints.open} /><Metric title="Open help requests" value={data.analytics.tickets.open} /><Metric title="Refunds waiting for action" value={data.analytics.refunds.pending} /><Metric title="Open safety issues" value={data.analytics.safety_reports.open} /><Metric title="Active staff" value={data.analytics.staff.active} /><Metric title="Unread alerts" value={data.analytics.notifications.unread} /></div><div className="grid gap-4 lg:grid-cols-3"><Distribution title="Complaints by status" values={data.analytics.complaints.status_distribution} /><Distribution title="Help requests by status" values={data.analytics.tickets.status_distribution} /><Distribution title="Refunds by status" values={data.analytics.refunds.status_distribution} /></div></div>}

    <AssignModal isOpen={!!caseToAssign} onClose={() => setCaseToAssign(null)} itemLabel={caseToAssign ? `${label(caseToAssign.type)} #${caseToAssign.id}` : 'case'} assignees={assigneesQuery.data || []} onAssign={async (staffId) => { await operationsApi.assignCase(caseToAssign.type, caseToAssign.id, staffId); await refresh(); setCaseToAssign(null) }} />
  </div>
}

const Empty = ({ text }: { text: string }) => <p className="py-8 text-center text-sm text-slate-500">{text}</p>
const FollowUpItem = ({ item, onChanged }: { item: any; onChanged: () => void }) => {
  const [editing, setEditing] = useState(false)
  const [draft, setDraft] = useState({ note: item.note || '', follow_up_at: item.follow_up_at ? new Date(item.follow_up_at).toISOString().slice(0, 16) : '' })
  const update = async (values: Record<string, unknown>, message: string) => { await operationsApi.updateContact(item.id, values); await onChanged(); toast.success(message) }
  return <div className="py-3"><p className="text-sm font-medium capitalize">{label(item.channel)} · {label(item.outcome)}</p><p className="text-xs text-slate-500">{label(item.entity_type)} #{item.object_id} · Created {new Date(item.created_at).toLocaleString()}</p>{editing ? <div className="mt-2 space-y-2"><textarea className="input w-full rounded-lg border p-2 text-sm" value={draft.note} onChange={e => setDraft({ ...draft, note: e.target.value })} /><input className="input w-full rounded-lg border p-2 text-sm" type="datetime-local" value={draft.follow_up_at} onChange={e => setDraft({ ...draft, follow_up_at: e.target.value })} /><div className="flex gap-2"><Button size="sm" onClick={async () => { await update(draft, 'Follow-up rescheduled'); setEditing(false) }}>Save changes</Button><Button size="sm" variant="ghost" onClick={() => setEditing(false)}>Cancel editing</Button></div></div> : <p className="mt-1 text-sm text-slate-600">{item.note || 'No note added'}</p>}<div className="mt-2 flex flex-wrap items-center gap-2"><Badge className={item.state === 'overdue' ? 'bg-red-50 text-red-700' : item.state === 'due_today' ? 'bg-amber-50 text-amber-700' : 'bg-blue-50 text-blue-700'}>{item.state === 'overdue' ? `Overdue since ${new Date(item.follow_up_at).toLocaleString()}` : item.state === 'due_today' ? `Due today at ${new Date(item.follow_up_at).toLocaleTimeString()}` : `Due ${new Date(item.follow_up_at).toLocaleString()}`}</Badge><Button size="sm" variant="secondary" onClick={() => setEditing(true)}>Edit or reschedule</Button><Button size="sm" onClick={() => update({ status: 'completed' }, 'Follow-up completed')}>Mark completed</Button><Button size="sm" variant="ghost" onClick={() => update({ status: 'cancelled' }, 'Follow-up cancelled')}>Cancel follow-up</Button></div></div>
}
const SavedReplyItem = ({ item, canManage, onChanged }: { item: any; canManage: boolean; onChanged: () => void }) => {
  const [editing, setEditing] = useState(false)
  const [draft, setDraft] = useState(item)
  if (editing) return <div className="space-y-2 rounded-xl border border-slate-200 p-4"><Field label="Title"><input className="input" value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} /></Field><Field label="Category"><input className="input" value={draft.category} onChange={e => setDraft({ ...draft, category: e.target.value })} /></Field><Field label="Who can see it"><select className="input" value={draft.visibility} onChange={e => setDraft({ ...draft, visibility: e.target.value })}><option value="shared">User and store</option><option value="user">User</option><option value="store">Store</option><option value="internal">Support team only</option></select></Field><Field label="Reply"><textarea className="input" rows={5} value={draft.body} onChange={e => setDraft({ ...draft, body: e.target.value })} /></Field><div className="flex gap-2"><Button size="sm" onClick={async () => { await operationsApi.updateSavedReply(item.id, draft); setEditing(false); await onChanged(); toast.success('Ready reply updated') }}>Save reply</Button><Button size="sm" variant="ghost" onClick={() => setEditing(false)}>Cancel</Button></div></div>
  return <div className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-start gap-2"><div className="flex-1"><p className="font-semibold">{item.title}</p><p className="text-xs capitalize text-slate-500">Category: {item.category || 'General'} · Visible to: {label(item.visibility)}</p></div><Button size="sm" variant="ghost" onClick={() => { navigator.clipboard.writeText(item.body); toast.success('Reply copied') }} leftIcon={<Copy className="h-4 w-4" />}>Copy</Button>{canManage && <><Button size="sm" variant="secondary" onClick={() => setEditing(true)}>Edit</Button><Button size="sm" variant="ghost" onClick={async () => { await operationsApi.deactivateSavedReply(item.id); await onChanged(); toast.success('Ready reply deactivated') }}><Trash2 className="h-4 w-4" /></Button></>}</div><p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{item.body}</p></div>
}
const DeadlineBadge = ({ deadline }: { deadline?: { stage: string; state: string; remaining_seconds: number } | null }) => {
  if (!deadline) return null
  const seconds = Math.abs(deadline.remaining_seconds)
  const time = seconds < 3600 ? `${Math.max(1, Math.ceil(seconds / 60))} min` : `${Math.ceil(seconds / 3600)} hr`
  const action = deadline.stage === 'first_reply' ? 'Send first reply' : 'Resolve this case'
  if (deadline.state === 'paused') return <Badge className="bg-blue-50 text-blue-700">Timer paused: waiting for customer information</Badge>
  if (deadline.state === 'overdue') return <Badge className="bg-red-50 text-red-700">Deadline missed: {action} was due {time} ago</Badge>
  if (deadline.state === 'due_soon') return <Badge className="bg-amber-50 text-amber-700">Action needed soon: {action} within {time}</Badge>
  return <Badge className="bg-emerald-50 text-emerald-700">Time available: {action} within {time}</Badge>
}
const SlaReadOnly = ({ policies }: { policies: any[] }) => <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-2">Case</th><th>Priority</th><th>First reply</th><th>Resolution</th></tr></thead><tbody>{policies.map(p => <tr key={p.id} className="border-b"><td className="p-2">{label(p.entity_type)}</td><td>{priorityLabel(p.priority)}</td><td>{p.first_response_minutes} min</td><td>{p.resolution_minutes} min</td></tr>)}</tbody></table></div>
const SlaSettings = ({ onChanged }: { onChanged: () => void }) => {
  const qc = useQueryClient()
  const query = useQuery({ queryKey: ['sla-settings'], queryFn: operationsApi.getSlaSettings })
  const [holiday, setHoliday] = useState({ date: '', name: '' })
  if (query.isLoading) return <Loading />
  const refreshSettings = async () => { await qc.invalidateQueries({ queryKey: ['sla-settings'] }); await onChanged() }
  return <div className="space-y-4"><Card title="Response deadline settings" subtitle="Times are entered in minutes. Choose whether only office hours count."><div className="space-y-3">{query.data?.policies.map((policy: any) => <SlaPolicyRow key={policy.id} initial={policy} onSaved={refreshSettings} />)}</div></Card><Card title="Support holidays" subtitle="Office-hours timers do not run on active holiday dates"><div className="flex flex-wrap gap-2"><input type="date" className="input rounded-lg border px-3 py-2 text-sm" value={holiday.date} onChange={e => setHoliday({ ...holiday, date: e.target.value })} /><input className="input min-w-52 rounded-lg border px-3 py-2 text-sm" placeholder="Holiday name" value={holiday.name} onChange={e => setHoliday({ ...holiday, name: e.target.value })} /><Button disabled={!holiday.date || !holiday.name} onClick={async () => { await operationsApi.addHoliday(holiday); setHoliday({ date: '', name: '' }); await refreshSettings(); toast.success('Holiday added') }}>Add holiday</Button></div><div className="mt-3 divide-y">{query.data?.holidays.map((item: any) => <div key={item.id} className="flex items-center gap-3 py-2 text-sm"><span className="flex-1">{new Date(`${item.date}T00:00:00`).toLocaleDateString()} · {item.name}</span><Button size="sm" variant="ghost" onClick={async () => { await operationsApi.removeHoliday(item.id); await refreshSettings() }}><Trash2 className="h-4 w-4" /></Button></div>)}</div></Card></div>
}
const SlaPolicyRow = ({ initial, onSaved }: { initial: any; onSaved: () => Promise<void> }) => {
  const [policy, setPolicy] = useState(initial)
  return <div className="rounded-xl border border-slate-200 p-3"><div className="grid gap-3 md:grid-cols-4"><div><p className="font-semibold">{label(policy.entity_type)}</p><p className="text-xs text-slate-500">{priorityLabel(policy.priority)}</p></div><Field label="First reply (minutes)"><input className="input" type="number" min="1" value={policy.first_response_minutes} onChange={e => setPolicy({ ...policy, first_response_minutes: Number(e.target.value) })} /></Field><Field label="Resolve (minutes)"><input className="input" type="number" min="1" value={policy.resolution_minutes} onChange={e => setPolicy({ ...policy, resolution_minutes: Number(e.target.value) })} /></Field><Field label="Warn before (minutes)"><input className="input" type="number" min="1" value={policy.warning_minutes} onChange={e => setPolicy({ ...policy, warning_minutes: Number(e.target.value) })} /></Field></div><div className="mt-3 flex flex-wrap gap-4 text-xs text-slate-700"><Check label="Count office hours only" checked={policy.working_hours_only} onChange={value => setPolicy({ ...policy, working_hours_only: value })} /><Check label="Pause while waiting for customer" checked={policy.pause_when_waiting} onChange={value => setPolicy({ ...policy, pause_when_waiting: value })} /><Check label="Alert senior team when late" checked={policy.auto_escalate} onChange={value => setPolicy({ ...policy, auto_escalate: value })} /><Check label="Automatically assign new cases" checked={policy.auto_assign} onChange={value => setPolicy({ ...policy, auto_assign: value })} /><Check label="Rule active" checked={policy.is_active} onChange={value => setPolicy({ ...policy, is_active: value })} /></div>{policy.working_hours_only && <div className="mt-3 space-y-3"><div className="grid gap-3 md:grid-cols-2"><Field label="Office opens"><input className="input" type="time" value={policy.workday_start?.slice(0, 5)} onChange={e => setPolicy({ ...policy, workday_start: e.target.value })} /></Field><Field label="Office closes"><input className="input" type="time" value={policy.workday_end?.slice(0, 5)} onChange={e => setPolicy({ ...policy, workday_end: e.target.value })} /></Field></div><div><p className="mb-1 text-xs font-medium text-slate-600">Working days</p><div className="flex flex-wrap gap-3">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((day, index) => <Check key={day} label={day} checked={(policy.working_days || []).includes(index)} onChange={checked => setPolicy({ ...policy, working_days: checked ? [...(policy.working_days || []), index].sort() : (policy.working_days || []).filter((value: number) => value !== index) })} />)}</div></div></div>}<div className="mt-3 flex justify-end"><Button size="sm" onClick={async () => { await operationsApi.updateSla(policy.id, policy); await onSaved(); toast.success('Deadline setting saved') }}>Save setting</Button></div></div>
}
const Check = ({ label: text, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) => <label className="flex items-center gap-2"><input type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)} />{text}</label>
const Metric = ({ title, value }: { title: string; value: number }) => <Card><p className="text-sm text-slate-500">{title}</p><p className="mt-2 text-3xl font-bold text-slate-900">{value}</p></Card>
const Distribution = ({ title, values }: { title: string; values: Record<string, number> }) => <Card title={title}><div className="space-y-2">{Object.entries(values || {}).map(([key, value]) => <div key={key} className="flex justify-between text-sm"><span className="capitalize text-slate-600">{label(key)}</span><strong>{value}</strong></div>)}</div></Card>
const Field = ({ label, children }: { label: string; children: React.ReactNode }) => <label className="block text-sm font-medium text-slate-700">{label}<div className="mt-1 [&_.input]:w-full [&_.input]:rounded-lg [&_.input]:border [&_.input]:border-slate-300 [&_.input]:bg-white [&_.input]:px-3 [&_.input]:py-2 [&_.input]:text-sm">{children}</div></label>
