from django.urls import path
from .views import (
    LoginView, RefreshTokenView, LogoutView, MeView, ChangePasswordView,
    DashboardSummaryView,
    StaffListCreateView, StaffDetailView, StaffActivateView, StaffResetPasswordView,
    ComplaintListView, ComplaintDetailView, ComplaintAssignView, ComplaintReplyView,
    ComplaintInternalNoteView, ComplaintStatusUpdateView, ComplaintBulkAssignView, ComplaintBulkCloseView,
    TicketListView, TicketDetailView, TicketReplyView, TicketStatusUpdateView,
    RefundListCreateView, RefundDetailView, RefundReviewView,
    SafetyReportListView, SafetyReportDetailView, SafetyReportActionView,
    UserLookupView, UserDetailView,
    StoreLookupView, StoreDetailView,
    NotificationListView, NotificationMarkReadView, NotificationUnreadCountView,
    AuditLogListView,
)

urlpatterns = [
    path("auth/login/", LoginView.as_view(), name="login"),
    path("auth/refresh/", RefreshTokenView.as_view(), name="refresh"),
    path("auth/logout/", LogoutView.as_view(), name="logout"),
    path("auth/me/", MeView.as_view(), name="me"),
    path("auth/change-password/", ChangePasswordView.as_view(), name="change-password"),
    path("dashboard/summary/", DashboardSummaryView.as_view(), name="dashboard-summary"),
    path("staff/", StaffListCreateView.as_view(), name="staff-list"),
    path("staff/<int:pk>/", StaffDetailView.as_view(), name="staff-detail"),
    path("staff/<int:pk>/activate/", StaffActivateView.as_view(), name="staff-activate"),
    path("staff/<int:pk>/reset-password/", StaffResetPasswordView.as_view(), name="staff-reset-password"),
    path("complaints/", ComplaintListView.as_view(), name="complaint-list"),
    path("complaints/<int:complaint_id>/", ComplaintDetailView.as_view(), name="complaint-detail"),
    path("complaints/<int:complaint_id>/assign/", ComplaintAssignView.as_view(), name="complaint-assign"),
    path("complaints/<int:complaint_id>/reply/", ComplaintReplyView.as_view(), name="complaint-reply"),
    path("complaints/<int:complaint_id>/notes/", ComplaintInternalNoteView.as_view(), name="complaint-notes"),
    path("complaints/<int:complaint_id>/status/", ComplaintStatusUpdateView.as_view(), name="complaint-status"),
    path("complaints/bulk-assign/", ComplaintBulkAssignView.as_view(), name="complaint-bulk-assign"),
    path("complaints/bulk-close/", ComplaintBulkCloseView.as_view(), name="complaint-bulk-close"),
    path("tickets/", TicketListView.as_view(), name="ticket-list"),
    path("tickets/<int:ticket_id>/", TicketDetailView.as_view(), name="ticket-detail"),
    path("tickets/<int:ticket_id>/reply/", TicketReplyView.as_view(), name="ticket-reply"),
    path("tickets/<int:ticket_id>/status/", TicketStatusUpdateView.as_view(), name="ticket-status"),
    path("refunds/", RefundListCreateView.as_view(), name="refund-list"),
    path("refunds/<int:pk>/", RefundDetailView.as_view(), name="refund-detail"),
    path("refunds/<int:pk>/review/", RefundReviewView.as_view(), name="refund-review"),
    path("safety-reports/", SafetyReportListView.as_view(), name="safety-report-list"),
    path("safety-reports/<int:pk>/", SafetyReportDetailView.as_view(), name="safety-report-detail"),
    path("safety-reports/<int:report_id>/action/", SafetyReportActionView.as_view(), name="safety-report-action"),
    path("users/search/", UserLookupView.as_view(), name="user-search"),
    path("users/<int:user_id>/", UserDetailView.as_view(), name="user-detail"),
    path("stores/search/", StoreLookupView.as_view(), name="store-search"),
    path("stores/<int:store_id>/", StoreDetailView.as_view(), name="store-detail"),
    path("notifications/", NotificationListView.as_view(), name="notification-list"),
    path("notifications/<int:notification_id>/read/", NotificationMarkReadView.as_view(), name="notification-mark-read"),
    path("notifications/unread-count/", NotificationUnreadCountView.as_view(), name="notification-unread-count"),
    path("audit-logs/", AuditLogListView.as_view(), name="audit-log-list"),
]
