# Generated by Django 6.0.7 on 2026-07-18 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('emergency_services', '0003_set_refund_wait_15_minutes'),
        ('prescription', '0103_emergency_request_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('complaint', 'Complaint'), ('ticket', 'Support Ticket'), ('refund', 'Refund Request'), ('safety_report', 'Safety Report')], max_length=50)),
                ('priority', models.CharField(max_length=20)),
                ('first_response_minutes', models.PositiveIntegerField()),
                ('resolution_minutes', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'is_active'], name='support_adm_entity__55d4f9_idx')],
                'unique_together': {('entity_type', 'priority')},
            },
        ),
        migrations.CreateModel(
            name='SupportStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('agent', 'Agent'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_staff', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='support_admin.supportstaff')),
            ],
        ),
        migrations.CreateModel(
            name='SupportNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='support_admin.supportstaff')),
            ],
        ),
        migrations.CreateModel(
            name='SupportAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('old_data', models.JSONField(blank=True, default=dict)),
                ('new_data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='support_admin.supportstaff')),
            ],
        ),
        migrations.CreateModel(
            name='SupportAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to='support_admin.supportstaff')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='support_admin.supportstaff')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyReportAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('reviewed', 'Reviewed'), ('warning_sent', 'Warning Sent'), ('account_suspended', 'Account Suspended'), ('account_restored', 'Account Restored'), ('escalated', 'Escalated'), ('closed', 'Closed')], max_length=30)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to='prescription.safetyreport')),
                ('target_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescription.store')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support_admin.supportstaff')),
            ],
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('rejection_reason', models.TextField(blank=True)),
                ('payment_gateway', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_refund_requests', to='emergency_services.emergencybroadcastcharge')),
                ('prescription_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_refund_requests', to='prescription.prescriptionresponse')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_refunds', to='support_admin.supportstaff')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_refunds', to='support_admin.supportstaff')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_refunds', to='support_admin.supportstaff')),
            ],
        ),
        migrations.CreateModel(
            name='InternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('body', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_notes', to='support_admin.supportstaff')),
            ],
        ),
        migrations.AddIndex(
            model_name='supportstaff',
            index=models.Index(fields=['role', 'is_active'], name='support_adm_role_688656_idx'),
        ),
        migrations.AddIndex(
            model_name='supportstaff',
            index=models.Index(fields=['is_active', 'created_at'], name='support_adm_is_acti_bbf705_idx'),
        ),
        migrations.AddIndex(
            model_name='supportnotification',
            index=models.Index(fields=['recipient', 'is_read', 'created_at'], name='support_adm_recipie_0aaf18_idx'),
        ),
        migrations.AddIndex(
            model_name='supportnotification',
            index=models.Index(fields=['entity_type', 'entity_id'], name='support_adm_entity__2fe8c3_idx'),
        ),
        migrations.AddIndex(
            model_name='supportauditlog',
            index=models.Index(fields=['actor', 'created_at'], name='support_adm_actor_i_af0ac2_idx'),
        ),
        migrations.AddIndex(
            model_name='supportauditlog',
            index=models.Index(fields=['entity_type', 'entity_id', 'created_at'], name='support_adm_entity__e0acef_idx'),
        ),
        migrations.AddIndex(
            model_name='supportauditlog',
            index=models.Index(fields=['action', 'created_at'], name='support_adm_action_27129d_idx'),
        ),
        migrations.AddIndex(
            model_name='supportassignment',
            index=models.Index(fields=['content_type', 'object_id', 'is_active'], name='support_adm_content_d08988_idx'),
        ),
        migrations.AddIndex(
            model_name='supportassignment',
            index=models.Index(fields=['assigned_to', 'is_active'], name='support_adm_assigne_e3f7e9_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyreportaction',
            index=models.Index(fields=['report', 'created_at'], name='support_adm_report__f73ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyreportaction',
            index=models.Index(fields=['admin', 'created_at'], name='support_adm_admin_i_824bec_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['status', 'created_at'], name='support_adm_status_993147_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['assigned_to', 'status'], name='support_adm_assigne_46cb9e_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['charge', 'status'], name='support_adm_charge__c13f23_idx'),
        ),
        migrations.AddIndex(
            model_name='internalnote',
            index=models.Index(fields=['content_type', 'object_id', 'is_deleted'], name='support_adm_content_a7e907_idx'),
        ),
        migrations.AddIndex(
            model_name='internalnote',
            index=models.Index(fields=['created_by', 'created_at'], name='support_adm_created_3fa3a9_idx'),
        ),
    ]
