# Generated by Django 6.0.7 on 2026-07-18 20:54

from django.db import migrations, models


def preserve_existing_staff_access(apps, schema_editor):
    SupportStaff = apps.get_model('support_admin', 'SupportStaff')
    SupportStaff.objects.update(all_cities_access=True)


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_services', '0004_emergencybroadcastcharge_policy_snapshot_and_more'),
        ('support_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportstaff',
            name='all_cities_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportstaff',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='support_staff', to='emergency_services.city'),
        ),
        migrations.RunPython(preserve_existing_staff_access, migrations.RunPython.noop),
    ]
