# Generated by Django 6.0.7 on 2026-07-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_admin', '0002_supportstaff_all_cities_access_supportstaff_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyreportaction',
            name='action',
            field=models.CharField(choices=[('reviewed', 'Reviewed'), ('warning_sent', 'Warning Sent'), ('account_suspended', 'Account Suspended'), ('account_restored', 'Account Restored'), ('escalated', 'Escalated'), ('closed', 'Closed'), ('assigned', 'Assigned')], max_length=30),
        ),
    ]
