# Generated by Django 6.0.7 on 2026-07-19 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('support_admin', '0003_alter_safetyreportaction_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('channel', models.CharField(choices=[('call', 'Call'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('other', 'Other')], max_length=20)),
                ('outcome', models.CharField(choices=[('contacted', 'Contacted'), ('no_answer', 'No answer'), ('callback', 'Callback requested'), ('message_sent', 'Message sent'), ('resolved', 'Resolved')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_logs', to='support_admin.supportstaff')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id', 'created_at'], name='support_adm_content_518bf5_idx'), models.Index(fields=['follow_up_at'], name='support_adm_follow__e4c872_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedReplyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('visibility', models.CharField(choices=[('user', 'User'), ('store', 'Store'), ('shared', 'Shared'), ('internal', 'Internal')], default='shared', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_replies', to='support_admin.supportstaff')),
            ],
            options={
                'ordering': ['category', 'title'],
                'indexes': [models.Index(fields=['is_active', 'category'], name='support_adm_is_acti_ebf4ae_idx')],
            },
        ),
    ]
