# Generated by Django 6.0.7 on 2026-07-19 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_admin', '0007_caseslaclock_paused_business_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=30)),
                ('entity_id', models.PositiveBigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('triaged', 'Triaged'), ('in_progress', 'In progress'), ('fixed', 'Fixed'), ('closed', 'Closed')], default='open', max_length=20)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('external_reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engineering_issues', to='support_admin.supportstaff')),
            ],
        ),
        migrations.CreateModel(
            name='SensitiveActionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=30)),
                ('entity_id', models.PositiveBigIntegerField(db_index=True)),
                ('action_type', models.CharField(choices=[('account_suspend', 'Suspend account'), ('account_restore', 'Restore account'), ('personal_data_change', 'Change personal data'), ('high_value_refund', 'High-value refund')], max_length=30)),
                ('reason', models.TextField()),
                ('verification_method', models.CharField(max_length=50)),
                ('verification_reference', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensitive_action_requests', to='support_admin.supportstaff')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sensitive_actions', to='support_admin.supportstaff')),
            ],
        ),
        migrations.CreateModel(
            name='CaseEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=30)),
                ('entity_id', models.PositiveBigIntegerField(db_index=True)),
                ('destination', models.CharField(choices=[('supervisor', 'Supervisor'), ('technical', 'Technical team'), ('emergency', 'Emergency team'), ('legal', 'Legal team')], max_length=20)),
                ('reason', models.TextField()),
                ('handover_note', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escalated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_escalations', to='support_admin.supportstaff')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_case_escalations', to='support_admin.supportstaff')),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'status'], name='support_adm_entity__abac36_idx')],
            },
        ),
        migrations.CreateModel(
            name='CaseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=30)),
                ('source_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=30)),
                ('target_id', models.PositiveBigIntegerField()),
                ('relation', models.CharField(choices=[('related', 'Related'), ('duplicate', 'Duplicate'), ('caused_by', 'Caused by')], default='related', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_relations', to='support_admin.supportstaff')),
            ],
            options={
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='support_adm_source__63787c_idx'), models.Index(fields=['target_type', 'target_id'], name='support_adm_target__5a8cf3_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_id', 'target_type', 'target_id'), name='unique_support_case_relation')],
            },
        ),
    ]
