# Generated by Django 6.0.7 on 2026-07-19 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_admin', '0008_engineeringissue_sensitiveactionrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserelation',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caserelation',
            name='merged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_case_merges', to='support_admin.supportstaff'),
        ),
    ]
