# Generated by Django 6.0.7 on 2026-07-18 22:17

import django.db.models.deletion
from django.db import migrations, models


def backfill_scope_and_city(apps, schema_editor):
    Complaint = apps.get_model('complaints', 'Complaint')
    Ticket = apps.get_model('complaints', 'PlatformSupportTicket')
    City = apps.get_model('emergency_services', 'City')
    default_city = City.objects.filter(is_default=True).order_by('pk').first()

    for complaint in Complaint.objects.select_related(
        'order__prescription', 'respondent_store', 'complainant_store'
    ).iterator():
        source = complaint.order.prescription if complaint.order_id else None
        source = source or complaint.respondent_store or complaint.complainant_store
        complaint.scope = 'CITY'
        complaint.city_id = getattr(source, 'city_id', None) or getattr(default_city, 'id', None)
        complaint.service_zone_id = getattr(source, 'service_zone_id', None)
        complaint.save(update_fields=['scope', 'city', 'service_zone'])

    global_categories = {'app_bug', 'account', 'technical', 'feature', 'other'}
    for ticket in Ticket.objects.select_related('requester_store').iterator():
        if ticket.category in global_categories:
            ticket.scope, ticket.city_id, ticket.service_zone_id = 'GLOBAL', None, None
        else:
            ticket.scope = 'CITY'
            ticket.city_id = getattr(ticket.requester_store, 'city_id', None) or getattr(default_city, 'id', None)
            ticket.service_zone_id = getattr(ticket.requester_store, 'service_zone_id', None)
        ticket.save(update_fields=['scope', 'city', 'service_zone'])


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaintmessage_visibility'),
        ('emergency_services', '0008_city_boundary_mode_city_center_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='emergency_services.city'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='scope',
            field=models.CharField(choices=[('CITY', 'City'), ('GLOBAL', 'Global')], db_index=True, default='CITY', max_length=10),
        ),
        migrations.AddField(
            model_name='complaint',
            name='service_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='emergency_services.servicezone'),
        ),
        migrations.AddField(
            model_name='platformsupportticket',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='emergency_services.city'),
        ),
        migrations.AddField(
            model_name='platformsupportticket',
            name='scope',
            field=models.CharField(choices=[('CITY', 'City'), ('GLOBAL', 'Global')], db_index=True, default='GLOBAL', max_length=10),
        ),
        migrations.AddField(
            model_name='platformsupportticket',
            name='service_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='emergency_services.servicezone'),
        ),
        migrations.RunPython(backfill_scope_and_city, migrations.RunPython.noop),
    ]
