from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("complaints", "0004_complaint_city_complaint_scope_and_more"), ("support_admin", "0006_sla_controls_and_holidays")]
    operations = [
        migrations.AddField(model_name="complaintmessage", name="support_staff", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="complaint_replies", to="support_admin.supportstaff")),
        migrations.AddField(model_name="complaintstatushistory", name="changed_by_staff", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="complaint_status_changes", to="support_admin.supportstaff")),
        migrations.AddField(model_name="platformsupportmessage", name="support_staff", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ticket_replies", to="support_admin.supportstaff")),
        migrations.CreateModel(name="PlatformSupportTicketStatusHistory", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("from_status", models.CharField(max_length=20)), ("to_status", models.CharField(max_length=20)), ("note", models.TextField(blank=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("changed_by_staff", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ticket_status_changes", to="support_admin.supportstaff")), ("ticket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="status_history", to="complaints.platformsupportticket"))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="SupportCaseRating", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("rating", models.PositiveSmallIntegerField()), ("feedback", models.TextField(blank=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("complaint", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="support_rating", to="complaints.complaint")), ("ticket", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="support_rating", to="complaints.platformsupportticket")), ("submitted_by_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="support_case_ratings", to="prescription.user")), ("submitted_by_store", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="support_case_ratings", to="prescription.store")), ("credited_staff", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="customer_ratings", to="support_admin.supportstaff"))]),
    ]
