# Generated by Django 5.0.7 on 2025-04-13 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_user_alter_store_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='token',
        ),
        migrations.AddField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='store_documents/'),
        ),
        migrations.AddField(
            model_name='store',
            name='drug_license_number',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='gst_number',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='store_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
    ]
