# Generated by Django 5.0.7 on 2025-04-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0005_remove_store_token_store_created_at_store_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='owner_id_proof',
            field=models.FileField(blank=True, null=True, upload_to='documents/id_proof/'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_license_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/licenses/'),
        ),
        migrations.AddField(
            model_name='store',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
