# Generated by Django 5.0.7 on 2025-04-13 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0006_store_is_active_store_owner_id_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='prescription.store'),
        ),
    ]
