# Generated by Django 5.0.7 on 2025-04-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0007_prescription_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='store',
        ),
        migrations.RemoveField(
            model_name='store',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='store',
            name='document',
        ),
        migrations.RemoveField(
            model_name='store',
            name='drug_license_number',
        ),
        migrations.RemoveField(
            model_name='store',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='store',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='store',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='store',
            name='owner_id_proof',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_image',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_license_document',
        ),
    ]
