# Generated by Django 5.0.7 on 2025-04-13 10:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0008_remove_prescription_store_remove_store_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='prescription.store'),
        ),
        migrations.AddField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='store_documents/'),
        ),
        migrations.AddField(
            model_name='store',
            name='drug_license_number',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='gst_number',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='owner_id_proof',
            field=models.FileField(blank=True, null=True, upload_to='documents/id_proof/'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_license_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/licenses/'),
        ),
    ]
