# Generated by Django 5.0.7 on 2025-04-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0009_prescription_store_store_created_at_store_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='store',
        ),
    ]
