# Generated by Django 5.0.7 on 2025-04-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0013_alter_prescription_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='store',
        ),
    ]
