# Generated by Django 5.0.7 on 2025-04-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0015_customtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
