# Generated by Django 5.0.7 on 2025-04-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0016_delete_customtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
