# Generated by Django 5.0.7 on 2025-04-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0017_prescription_latitude_prescription_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
