# Generated by Django 5.0.7 on 2025-04-27 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0019_prescription_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='user',
        ),
    ]
