# Generated by Django 5.0.7 on 2025-04-27 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0022_remove_prescription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='prescription.user'),
        ),
    ]
