# Generated by Django 5.0.7 on 2025-04-27 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0023_prescription_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.prescription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.user')),
            ],
        ),
    ]
