# Generated by Django 5.0.7 on 2025-04-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0024_prescriptionresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrescriptionResponse',
        ),
    ]
