# Generated by Django 5.0.7 on 2025-04-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0026_prescriptionresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionresponse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='response_images/'),
        ),
    ]
