# Generated by Django 5.0.7 on 2025-04-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0027_prescriptionresponse_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionresponse',
            name='store_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionresponse',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
