# Generated by Django 5.0.7 on 2025-04-27 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0028_prescriptionresponse_store_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionresponse',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='prescription.store'),
        ),
    ]
