# Generated by Django 5.0.7 on 2025-05-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0029_prescriptionresponse_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionresponse',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='response_images/'),
        ),
    ]
