# Generated by Django 5.0.7 on 2025-05-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0030_alter_prescriptionresponse_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
