# Generated by Django 5.0.7 on 2025-05-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0031_prescription_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionresponse',
            name='store_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionresponse',
            name='store_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionresponse',
            name='store_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
