# Generated by Django 5.0.7 on 2025-05-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0032_prescriptionresponse_store_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionresponse',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
