# Generated by Django 5.0.7 on 2025-05-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0033_prescriptionresponse_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionresponse',
            name='total_amount',
        ),
    ]
