# Generated by Django 5.0.7 on 2025-05-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0034_remove_prescriptionresponse_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionresponse',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
