# Generated by Django 5.0.7 on 2025-05-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0035_prescriptionresponse_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionresponse',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance from user in kilometers', max_digits=5, null=True),
        ),
    ]
