# Generated by Django 5.0.7 on 2025-05-27 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0036_prescriptionresponse_distance_km'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='user_address',
        ),
    ]
