# Generated by Django 5.0.7 on 2025-05-27 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0037_rename_address_user_user_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='address',
            new_name='user_address',
        ),
    ]
