# Generated by Django 5.0.7 on 2025-05-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0038_rename_address_prescription_user_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='user_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_address',
            new_name='address',
        ),
    ]
