# Generated by Django 5.0.7 on 2025-05-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0039_rename_user_address_prescription_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='address',
            new_name='user_address',
        ),
    ]
