# Generated by Django 5.0.7 on 2025-05-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0041_prescriptionresponsemedicine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrescriptionResponseMedicine',
        ),
    ]
