# Generated by Django 5.0.7 on 2025-05-30 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0042_delete_prescriptionresponsemedicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionResponseMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='prescription.prescriptionresponse')),
            ],
        ),
    ]
