# Generated by Django 5.0.7 on 2025-06-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0043_prescriptionresponsemedicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionresponse',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
