# Generated by Django 5.0.7 on 2025-06-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0045_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
