# Generated by Django 5.0.7 on 2025-06-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0046_store_expo_push_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='expo_push_token',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
