# Generated by Django 5.2.4 on 2025-07-17 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0047_remove_store_expo_push_token_delete_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionTargetStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_stores', to='prescription.prescription')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_prescriptions', to='prescription.store')),
            ],
        ),
    ]
