# Generated by Django 5.2.4 on 2025-07-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0048_prescriptiontargetstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('emergency', 'Emergency')], default='normal', max_length=20),
        ),
    ]
