# Generated by Django 5.2.4 on 2025-07-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0049_prescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionresponse',
            name='user_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
