# Generated by Django 5.2.4 on 2025-07-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0050_prescriptionresponse_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionresponse',
            name='user_contact_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
