# Generated by Django 5.2.4 on 2025-07-18 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0051_prescriptionresponse_user_contact_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='prescription.prescriptionresponse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.user')),
            ],
        ),
    ]
