# Generated by Django 5.2.4 on 2025-07-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0052_reportnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionresponse',
            name='store_contact_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
