# Generated by Django 5.2.6 on 2026-04-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0056_chatthread_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='chat_audio/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
