# Generated by Django 5.2.6 on 2026-04-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0060_alter_chatmessage_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionresponse',
            name='distance_km',
        ),
        migrations.AddField(
            model_name='prescriptionresponse',
            name='delivery_option',
            field=models.CharField(blank=True, choices=[('walk_in', 'Walk-in'), ('online', 'Online Delivery')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
