# Generated by Django 5.2.6 on 2026-04-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0061_remove_prescriptionresponse_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionresponse',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance from user in kilometers', max_digits=5, null=True),
        ),
    ]
