# Generated by Django 5.2.6 on 2026-04-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0062_prescriptionresponse_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionresponse',
            name='stock_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionresponsemedicine',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
