# Generated by Django 5.2.6 on 2026-04-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0063_prescriptionresponse_stock_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionresponsemedicine',
            name='medicine_brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
