# Generated by Django 5.2.6 on 2026-04-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0064_prescriptionresponsemedicine_medicine_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionresponse',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescriptionresponse',
            name='is_unresponsive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescriptionresponse',
            name='last_refresh_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionresponse',
            name='response_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='prescriptionresponse',
            name='user_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
