# Generated by Django 5.2.6 on 2026-04-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0065_prescriptionresponse_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionresponse',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionresponse',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionresponse',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionresponse',
            name='is_packed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescriptionresponse',
            name='is_processing_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescriptionresponse',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionresponse',
            name='processing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionresponse',
            name='user_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('processing', 'Processing'), ('locked', 'Locked'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('dismissed', 'Dismissed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
