# Generated by Django 5.2.6 on 2026-04-22 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0066_prescriptionresponse_accepted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_by', models.CharField(choices=[('user', 'User'), ('store', 'Store')], max_length=10)),
                ('target_type', models.CharField(choices=[('user', 'User'), ('store', 'Store')], max_length=10)),
                ('rating', models.PositiveSmallIntegerField()),
                ('review', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='prescription.prescriptionresponse')),
            ],
            options={
                'unique_together': {('order', 'given_by')},
            },
        ),
    ]
