# Generated by Django 5.2.6 on 2026-04-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0067_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='WSEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('event_type', models.CharField(max_length=50)),
                ('user_id', models.IntegerField(db_index=True)),
                ('response_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='prescriptio_user_id_d45da3_idx')],
            },
        ),
    ]
