# Generated by Django 5.2.6 on 2026-04-27 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0068_ws_event_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionResponseStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('processing', 'Processing'), ('locked', 'Locked'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('dismissed', 'Dismissed'), ('expired', 'Expired')], max_length=20)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('processing', 'Processing'), ('locked', 'Locked'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('dismissed', 'Dismissed'), ('expired', 'Expired')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='prescription.prescriptionresponse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
