# Generated by Django 5.2.6 on 2026-04-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0069_prescriptionresponsestatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='store',
            name='avg_response_time_mins',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='store',
            name='geohash',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
