# Generated by Django 5.2.6 on 2026-04-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0070_store_average_rating_store_avg_response_time_mins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionresponse',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('store', 'Store'), ('system', 'System')], max_length=10, null=True),
        ),
    ]
