# Generated by Django 5.2.6 on 2026-04-27 15:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0071_alter_prescriptionresponse_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='store',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, null=True, srid=4326),
        ),
    ]
