# Generated by Django 5.2.6 on 2026-04-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0072_prescription_location_store_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='geohash',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
    ]
