# Generated by Django 5.2.6 on 2026-04-27 16:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0073_prescription_geohash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, geography=True, null=True, srid=4326),
        ),
    ]
