# Generated by Django 5.2.6 on 2026-05-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0074_alter_prescription_location_alter_store_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionresponse',
            name='quotation_scenario',
            field=models.CharField(blank=True, choices=[('exact_brand', 'All Required Brands Available'), ('all_generic', 'All Generics Available'), ('mixed', 'Mixed (Brand + Generic)'), ('substitutes', 'Alternative Brands / Substitutes'), ('partial', 'Partially Available')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionresponsemedicine',
            name='medicine_type',
            field=models.CharField(choices=[('brand', 'Original Brand'), ('generic', 'Generic Equivalent'), ('substitute', 'Different Brand / Substitute')], default='brand', max_length=20),
        ),
    ]
