# Generated by Django 5.2.6 on 2026-05-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0075_prescriptionresponse_quotation_scenario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cancelled_orders_count',
            field=models.IntegerField(default=0, help_text='Orders cancelled by the store'),
        ),
        migrations.AddField(
            model_name='store',
            name='completed_orders_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='quality_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='store',
            name='repeat_order_count',
            field=models.IntegerField(default=0, help_text='Number of repeat customers'),
        ),
    ]
