# Generated by Django 5.2.6 on 2026-05-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0076_store_cancelled_orders_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionresponse',
            name='quality_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='store',
            name='avg_delivery_time_mins',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='store',
            name='orders_won_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='quotes_sent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='store',
            name='cancelled_orders_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='store',
            name='repeat_order_count',
            field=models.IntegerField(default=0),
        ),
    ]
