# Generated by Django 5.2.6 on 2026-05-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0077_prescriptionresponse_quality_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='exposure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='total_completed_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
