# Generated by Django 5.2.6 on 2026-05-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0078_store_exposure_count_store_total_completed_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionresponse',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
