# Generated by Django 5.2.6 on 2026-05-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0079_prescriptionresponse_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionresponse',
            name='user_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('processing', 'Processing'), ('locked', 'Locked (Ready for Pickup)'), ('out_for_delivery', 'Out for Delivery'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('dismissed', 'Dismissed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptionresponsestatushistory',
            name='from_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('processing', 'Processing'), ('locked', 'Locked (Ready for Pickup)'), ('out_for_delivery', 'Out for Delivery'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('dismissed', 'Dismissed'), ('expired', 'Expired')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptionresponsestatushistory',
            name='to_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('processing', 'Processing'), ('locked', 'Locked (Ready for Pickup)'), ('out_for_delivery', 'Out for Delivery'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('dismissed', 'Dismissed'), ('expired', 'Expired')], max_length=20),
        ),
    ]
