# Generated by Django 5.2.6 on 2026-05-31 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0080_alter_prescriptionresponse_user_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionresponse',
            name='quotation_scenario',
            field=models.CharField(blank=True, choices=[('exact_brand', 'All Required Brands Available'), ('all_generic', 'All Generics Available'), ('mixed', 'Mixed (Brand + Generic)'), ('substitutes', 'Alternative Brands / Substitutes'), ('partial', 'Some Items Available')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AppRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_ratings', to='prescription.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_ratings', to='prescription.user')),
            ],
        ),
    ]
