# Generated by Django 5.2.6 on 2026-06-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0081_alter_prescriptionresponse_quotation_scenario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='auto_accept_prescription',
            field=models.BooleanField(default=False),
        ),
    ]
