# Generated by Django 5.2.6 on 2026-06-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0082_store_auto_accept_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionresponsemedicine',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
