# Generated by Django 5.2.6 on 2026-06-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0084_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='drug_license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='gst_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
