# Generated by Django 5.2.6 on 2026-06-21 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0085_alter_store_drug_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionresponse',
            name='completed_by_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_orders', to='prescription.store'),
        ),
        migrations.CreateModel(
            name='DeliveryOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_otp', to='prescription.prescriptionresponse')),
            ],
        ),
    ]
