# Generated by Django 5.2.6 on 2026-06-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0090_repeat_customer_order_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
