# Generated by Django 5.2.6 on 2026-07-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0091_prescription_description_prescription_medicine_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='ai_classification',
            field=models.CharField(choices=[('prescription', 'Prescription'), ('medicine', 'Medicine'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='ai_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='ai_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='ai_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='user_upload_type',
            field=models.CharField(choices=[('prescription', 'Prescription Image'), ('medicine', 'Medicine Box Photo'), ('text_only', 'Text Only')], default='text_only', max_length=20),
        ),
    ]
