# Generated by Codex
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0092_prescription_ai_classification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField(blank=True)),
                ('notification_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to='prescription.store')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to='prescription.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['recipient_user', 'is_read', 'created_at'], name='prescriptio_recipie_7a34fd_idx'),
                    models.Index(fields=['recipient_store', 'is_read', 'created_at'], name='prescriptio_recipie_600103_idx'),
                    models.Index(fields=['notification_type', 'created_at'], name='prescriptio_notific_ea08ab_idx'),
                ],
            },
        ),
    ]
