# Generated by Django 6.0.7 on 2026-07-15 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0094_store_report_prescription_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_type', models.CharField(choices=[('user', 'User'), ('store', 'Pharmacy')], db_index=True, max_length=10)),
                ('target_type', models.CharField(choices=[('user', 'User'), ('store', 'Pharmacy')], db_index=True, max_length=10)),
                ('category', models.CharField(choices=[('fake_or_spam', 'Fake or spam request'), ('invalid_contact', 'Invalid contact information'), ('wrong_information', 'Wrong information'), ('suspicious_behavior', 'Suspicious behavior'), ('medicine_safety', 'Medicine safety concern'), ('abusive_behavior', 'Abusive behavior'), ('other', 'Other')], db_index=True, default='other', max_length=40)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('action_taken', 'Action Taken'), ('closed', 'Closed')], db_index=True, default='submitted', max_length=20)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_reports', to='prescription.prescription')),
                ('reported_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_reports_received', to='prescription.store')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_reports_received', to='prescription.user')),
                ('reporter_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_reports_filed', to='prescription.store')),
                ('reporter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_reports_filed', to='prescription.user')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_reports', to='prescription.prescriptionresponse')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reporter_type', 'status', 'created_at'], name='prescriptio_reporte_5be453_idx')],
            },
        ),
    ]
