# Generated by Django 6.0.7 on 2026-07-15 17:09

from django.db import migrations


def migrate_reports(apps, schema_editor):
    SafetyReport = apps.get_model('prescription', 'SafetyReport')
    ReportNote = apps.get_model('prescription', 'ReportNote')
    StoreReportNote = apps.get_model('prescription', 'StoreReportNote')

    for legacy in ReportNote.objects.select_related('response__store').iterator():
        report = SafetyReport.objects.create(
            reporter_type='user', reporter_user_id=legacy.user_id,
            target_type='store', reported_store_id=legacy.response.store_id,
            prescription_id=legacy.response.prescription_id, response_id=legacy.response_id,
            category='other', description=legacy.note, status='submitted',
        )
        SafetyReport.objects.filter(pk=report.pk).update(created_at=legacy.created_at, updated_at=legacy.created_at)

    for legacy in StoreReportNote.objects.select_related('response', 'prescription').iterator():
        prescription_id = legacy.prescription_id or (legacy.response.prescription_id if legacy.response_id else None)
        reported_user_id = None
        if legacy.response_id:
            reported_user_id = legacy.response.user_id
        elif legacy.prescription_id:
            reported_user_id = legacy.prescription.user_id
        report = SafetyReport.objects.create(
            reporter_type='store', reporter_store_id=legacy.store_id,
            target_type='user', reported_user_id=reported_user_id,
            prescription_id=prescription_id, response_id=legacy.response_id,
            category='other', description=legacy.note, status='submitted',
        )
        SafetyReport.objects.filter(pk=report.pk).update(created_at=legacy.created_at, updated_at=legacy.created_at)


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0095_safety_report'),
    ]

    operations = [
        migrations.RunPython(migrate_reports, migrations.RunPython.noop),
    ]
