# Generated by Django 6.0.7 on 2026-07-15 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0096_migrate_legacy_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_pharmacist_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='pharmacist_available',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='pharmacist_license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='pharmacist_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='store',
            name='pharmacist_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PharmacistConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('how_to_take', 'How and when to take'), ('food_timing', 'Before or after food'), ('missed_dose', 'Missed dose'), ('side_effects', 'Common side effects'), ('storage', 'Storage'), ('prescription_help', 'Understand prescription'), ('other', 'Other')], max_length=30)),
                ('medicine_name', models.CharField(max_length=200)),
                ('question', models.TextField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting for pharmacist'), ('active', 'Active'), ('callback_requested', 'Callback requested'), ('answered', 'Answered'), ('closed', 'Closed')], db_index=True, default='waiting', max_length=30)),
                ('callback_requested', models.BooleanField(default=False)),
                ('callback_phone', models.CharField(blank=True, max_length=15)),
                ('callback_preferred_time', models.CharField(blank=True, max_length=100)),
                ('user_consent_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_consultation', to='prescription.prescriptionresponse')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_consultations', to='prescription.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_consultations', to='prescription.user')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacistConsultationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('pharmacist', 'Verified pharmacist')], max_length=20)),
                ('text', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='pharmacist_consultations/')),
                ('pharmacist_name_snapshot', models.CharField(blank=True, max_length=120)),
                ('pharmacist_license_snapshot', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='prescription.pharmacistconsultation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pharmacistconsultation',
            index=models.Index(fields=['store', 'status', 'updated_at'], name='prescriptio_store_i_36cfe5_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacistconsultation',
            index=models.Index(fields=['user', 'updated_at'], name='prescriptio_user_id_0fc505_idx'),
        ),
    ]
