# Generated by Django 6.0.7 on 2026-07-17 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0098_delivery_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReplacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('wrong_medicine', 'Wrong Medicine Delivered'), ('expired_medicine', 'Expired Medicine'), ('damaged', 'Damaged Packaging/Product'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='replacements/proofs/')),
                ('status', models.CharField(choices=[('requested', 'Replacement Requested'), ('approved', 'Approved by Store'), ('rejected', 'Rejected by Store'), ('in_transit', 'Replacement in Transit'), ('completed', 'Replacement Completed'), ('cancelled', 'Cancelled by User')], db_index=True, default='requested', max_length=30)),
                ('store_note', models.TextField(blank=True, help_text='Reason for rejection or instructions for replacement', null=True)),
                ('is_walk_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_request', to='prescription.prescriptionresponse')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to='prescription.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to='prescription.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'status', 'created_at'], name='prescriptio_store_i_8e3609_idx')],
            },
        ),
    ]
