# Generated by Django 6.0.7 on 2026-07-18 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_services', '0004_emergencybroadcastcharge_policy_snapshot_and_more'),
        ('prescription', '0103_emergency_request_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='emergency_services.city'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='service_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='emergency_services.servicezone'),
        ),
        migrations.AddField(
            model_name='prescriptiontargetstore',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_dispatches', to='emergency_services.city'),
        ),
        migrations.AddField(
            model_name='prescriptiontargetstore',
            name='escalated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiontargetstore',
            name='first_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiontargetstore',
            name='last_notification_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='prescriptiontargetstore',
            name='policy_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='prescriptiontargetstore',
            name='reminder_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescriptiontargetstore',
            name='second_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiontargetstore',
            name='service_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_dispatches', to='emergency_services.servicezone'),
        ),
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='emergency_services.city'),
        ),
        migrations.AddField(
            model_name='store',
            name='service_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='emergency_services.servicezone'),
        ),
    ]
