# Generated by Django 6.0.7 on 2026-07-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0104_prescription_city_prescription_service_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptiontargetstore',
            name='last_manual_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiontargetstore',
            name='manual_reminder_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescriptiontargetstore',
            name='reminders_suppressed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiontargetstore',
            name='reminders_suppressed_by_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiontargetstore',
            name='support_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptiontargetstore',
            name='support_contacted_by_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
