# Generated by Django 6.0.7 on 2026-07-19 05:05

import django.db.models.deletion
from django.db import migrations, models


def backfill_safety_scope(apps, schema_editor):
    SafetyReport = apps.get_model('prescription', 'SafetyReport')
    City = apps.get_model('emergency_services', 'City')
    default_city = City.objects.filter(is_default=True).order_by('pk').first()
    severity_map = {
        'medicine_safety': 'high',
        'suspicious_behavior': 'high',
        'abusive_behavior': 'medium',
        'fake_or_spam': 'medium',
        'wrong_information': 'medium',
        'invalid_contact': 'low',
        'other': 'medium',
    }
    reports = SafetyReport.objects.select_related(
        'prescription', 'response__prescription', 'reported_store', 'reporter_store'
    )
    for report in reports.iterator():
        source = report.prescription
        if not source and report.response_id:
            source = report.response.prescription
        source = source or report.reported_store or report.reporter_store
        report.severity = severity_map.get(report.category, 'medium')
        if source:
            report.scope = 'CITY'
            report.city_id = getattr(source, 'city_id', None) or getattr(default_city, 'id', None)
            report.service_zone_id = getattr(source, 'service_zone_id', None)
        else:
            report.scope = 'GLOBAL'
            report.city_id = None
            report.service_zone_id = None
        report.save(update_fields=['severity', 'scope', 'city', 'service_zone'])


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_services', '0008_city_boundary_mode_city_center_latitude_and_more'),
        ('prescription', '0105_prescriptiontargetstore_last_manual_reminder_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyreport',
            name='assigned_to_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_reports', to='emergency_services.city'),
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='scope',
            field=models.CharField(choices=[('CITY', 'City'), ('GLOBAL', 'Global')], db_index=True, default='GLOBAL', max_length=10),
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='service_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_reports', to='emergency_services.servicezone'),
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='safetyreport',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('action_taken', 'Action Taken'), ('escalated', 'Escalated'), ('closed', 'Closed')], db_index=True, default='submitted', max_length=20),
        ),
        migrations.RunPython(backfill_safety_scope, migrations.RunPython.noop),
    ]
