# Generated by Django 6.0.7 on 2026-07-22 17:07

from django.db import migrations, models


def preserve_existing_assignments(apps, schema_editor):
    QuoteDeliveryOffer = apps.get_model('prescription', 'QuoteDeliveryOffer')
    QuoteDeliveryOffer.objects.filter(
        assigned_delivery_person__isnull=False,
        response__user_status='out_for_delivery',
    ).update(assignment_status='accepted')


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0109_delivery_partner_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotedeliveryoffer',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotedeliveryoffer',
            name='assignment_rejection_reason',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='quotedeliveryoffer',
            name='assignment_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotedeliveryoffer',
            name='assignment_status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('pending', 'Waiting for Partner'), ('accepted', 'Accepted by Partner'), ('rejected', 'Rejected by Partner')], db_index=True, default='unassigned', max_length=20),
        ),
        migrations.AddField(
            model_name='quotedeliveryoffer',
            name='delivery_issue_code',
            field=models.CharField(blank=True, choices=[('customer_unreachable', 'Customer not answering'), ('wrong_address', 'Address is incorrect'), ('customer_unavailable', 'Customer unavailable'), ('order_not_ready', 'Order not ready at store'), ('vehicle_problem', 'Vehicle problem')], max_length=40),
        ),
        migrations.AddField(
            model_name='quotedeliveryoffer',
            name='delivery_issue_note',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='quotedeliveryoffer',
            name='delivery_issue_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(preserve_existing_assignments, migrations.RunPython.noop),
    ]
