# Generated by Django 6.0.7 on 2026-07-22 18:26

import django.db.models.deletion
from django.db import migrations, models


def preserve_existing_delivery_issues(apps, schema_editor):
    QuoteDeliveryOffer = apps.get_model('prescription', 'QuoteDeliveryOffer')
    DeliveryIssueReport = apps.get_model('prescription', 'DeliveryIssueReport')
    for offer in QuoteDeliveryOffer.objects.filter(
        delivery_issue_code__gt='',
        assigned_delivery_person__isnull=False,
    ).select_related('response'):
        terminal = offer.response.user_status in ('completed', 'cancelled')
        DeliveryIssueReport.objects.create(
            response_id=offer.response_id,
            delivery_person_id=offer.assigned_delivery_person_id,
            issue_code=offer.delivery_issue_code,
            note=offer.delivery_issue_note,
            status='resolved' if terminal else 'open',
            resolution_note='Order already closed.' if terminal else '',
            resolved_at=offer.response.completed_at if terminal else None,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0110_delivery_partner_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryIssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_code', models.CharField(choices=[('customer_unreachable', 'Customer not answering'), ('wrong_address', 'Address is incorrect'), ('customer_unavailable', 'Customer unavailable'), ('order_not_ready', 'Order not ready at store'), ('vehicle_problem', 'Vehicle problem')], max_length=40)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('resolution_note', models.CharField(blank=True, max_length=240)),
                ('reported_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='prescription.storedeliveryperson')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_issue_reports', to='prescription.prescriptionresponse')),
            ],
            options={
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['delivery_person', 'status', 'reported_at'], name='prescriptio_deliver_0749c9_idx')],
            },
        ),
        migrations.RunPython(preserve_existing_delivery_issues, migrations.RunPython.noop),
    ]
