# Generated by Django 6.0.7 on 2026-07-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0111_delivery_issue_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryissuereport',
            name='resolution_source',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
