# Generated by Django 6.0.7 on 2026-07-22 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0112_delivery_issue_resolution_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('customer_unreachable', 'Customer unreachable'), ('wrong_address', 'Wrong or incomplete address'), ('customer_refused', 'Customer refused delivery'), ('otp_unavailable', 'Customer could not provide OTP'), ('unsafe_location', 'Unsafe delivery location'), ('other', 'Other')], max_length=40)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('package_condition', models.CharField(choices=[('sealed', 'Sealed / intact'), ('opened', 'Package opened'), ('damaged', 'Package damaged')], default='sealed', max_length=20)),
                ('status', models.CharField(choices=[('returning', 'Returning to pharmacy'), ('received', 'Received by pharmacy'), ('disputed', 'Return disputed')], db_index=True, default='returning', max_length=20)),
                ('store_note', models.CharField(blank=True, max_length=240)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_returns', to='prescription.storedeliveryperson')),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_return', to='prescription.prescriptionresponse')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='prescriptio_status_01e6c8_idx')],
            },
        ),
    ]
