# Generated by Django 6.0.7 on 2026-07-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0115_activity_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='prescriptio_categor_e3fd3b_idx',
            old_name='prescr_cat_act_cr_6d1e6a_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='prescriptio_subject_f03031_idx',
            old_name='prescr_subj_typ_9b0e24_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='prescriptio_actor_t_f22d82_idx',
            old_name='prescr_act_typ_a6c01f_idx',
        ),
    ]
