# Generated by Django 6.0.7 on 2026-07-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencybroadcastcharge',
            name='last_refund_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='emergencybroadcastcharge',
            name='provider_refund_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='emergencybroadcastcharge',
            name='refund_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emergencybroadcastcharge',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergencybroadcastcharge',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Payment pending'), ('authorized', 'Authorized'), ('broadcasting', 'Broadcasting'), ('service_delivered', 'Service delivered'), ('refund_pending', 'Refund pending'), ('refund_failed', 'Refund failed'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('expired', 'Expired')], max_length=24),
        ),
    ]
