# Generated by Django 6.0.7 on 2026-07-17 17:31

from django.db import migrations, models


def set_existing_policy_to_15_minutes(apps, schema_editor):
    Policy = apps.get_model('emergency_services', 'EmergencyFeePolicy')
    Policy.objects.filter(quote_wait_minutes=10).update(quote_wait_minutes=15)


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_services', '0002_harden_automatic_refunds'),
    ]

    operations = [
        migrations.RunPython(set_existing_policy_to_15_minutes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='emergencyfeepolicy',
            name='quote_wait_minutes',
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
