# Generated by Django 6.0.7 on 2026-07-18 20:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_services', '0003_set_refund_wait_15_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencybroadcastcharge',
            name='policy_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emergencyfeepolicy',
            name='first_store_reminder_seconds',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='emergencyfeepolicy',
            name='max_store_reminders',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='emergencyfeepolicy',
            name='reminders_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emergencyfeepolicy',
            name='second_store_reminder_seconds',
            field=models.PositiveIntegerField(default=240),
        ),
        migrations.AddField(
            model_name='emergencyfeepolicy',
            name='support_escalation_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emergencyfeepolicy',
            name='support_escalation_seconds',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('state', 'name'),
                'unique_together': {('name', 'state')},
            },
        ),
        migrations.AddField(
            model_name='emergencybroadcastcharge',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_charges', to='emergency_services.city'),
        ),
        migrations.CreateModel(
            name='ServiceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_zones', to='emergency_services.city')),
            ],
            options={
                'ordering': ('city__name', 'name'),
                'unique_together': {('city', 'name')},
            },
        ),
        migrations.AddField(
            model_name='emergencybroadcastcharge',
            name='service_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_charges', to='emergency_services.servicezone'),
        ),
        migrations.CreateModel(
            name='CityEmergencyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_store_reminder_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('second_store_reminder_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('support_escalation_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('max_store_reminders', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reminders_enabled', models.BooleanField(blank=True, null=True)),
                ('support_escalation_enabled', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_policies', to='emergency_services.city')),
                ('service_zone', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_policy', to='emergency_services.servicezone')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('service_zone__isnull', True)), fields=('city',), name='unique_city_emergency_policy')],
            },
        ),
    ]
