# Generated by Django 6.0.7 on 2026-07-18 21:12

from django.db import migrations, models


def create_default_area_and_backfill(apps, schema_editor):
    City = apps.get_model('emergency_services', 'City')
    EmergencyBroadcastCharge = apps.get_model('emergency_services', 'EmergencyBroadcastCharge')
    Store = apps.get_model('prescription', 'Store')
    Prescription = apps.get_model('prescription', 'Prescription')
    PrescriptionTargetStore = apps.get_model('prescription', 'PrescriptionTargetStore')

    default_city, _ = City.objects.get_or_create(
        name='Default Service Area',
        state='Unassigned',
        defaults={
            'timezone': 'Asia/Kolkata',
            'is_active': True,
            'is_default': True,
        },
    )
    if not default_city.is_default:
        City.objects.filter(is_default=True).update(is_default=False)
        default_city.is_default = True
        default_city.is_active = True
        default_city.save(update_fields=['is_default', 'is_active'])

    Store.objects.filter(city__isnull=True).update(city=default_city)
    Prescription.objects.filter(city__isnull=True).update(city=default_city)
    PrescriptionTargetStore.objects.filter(city__isnull=True).update(city=default_city)
    EmergencyBroadcastCharge.objects.filter(city__isnull=True).update(city=default_city)


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_services', '0004_emergencybroadcastcharge_policy_snapshot_and_more'),
        ('prescription', '0104_prescription_city_prescription_service_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='single_default_service_city'),
        ),
        migrations.RunPython(create_default_area_and_backfill, migrations.RunPython.noop),
    ]
