# Generated by Django 6.0.7 on 2026-07-18 21:21

from django.db import migrations, models


def apply_confirmed_default_timings(apps, schema_editor):
    EmergencyFeePolicy = apps.get_model('emergency_services', 'EmergencyFeePolicy')
    EmergencyFeePolicy.objects.filter(
        first_store_reminder_seconds=120,
        second_store_reminder_seconds=240,
        support_escalation_seconds=300,
    ).update(
        first_store_reminder_seconds=60,
        second_store_reminder_seconds=120,
        support_escalation_seconds=180,
        normal_first_store_reminder_seconds=180,
        normal_second_store_reminder_seconds=300,
        normal_support_escalation_seconds=420,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_services', '0005_city_is_default_city_single_default_service_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityemergencypolicy',
            name='normal_first_store_reminder_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityemergencypolicy',
            name='normal_second_store_reminder_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityemergencypolicy',
            name='normal_support_escalation_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyfeepolicy',
            name='normal_first_store_reminder_seconds',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name='emergencyfeepolicy',
            name='normal_second_store_reminder_seconds',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='emergencyfeepolicy',
            name='normal_support_escalation_seconds',
            field=models.PositiveIntegerField(default=420),
        ),
        migrations.AlterField(
            model_name='emergencyfeepolicy',
            name='first_store_reminder_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='emergencyfeepolicy',
            name='second_store_reminder_seconds',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='emergencyfeepolicy',
            name='support_escalation_seconds',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.RunPython(apply_confirmed_default_timings, migrations.RunPython.noop),
    ]
