# Generated by Django 6.0.7 on 2026-07-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_services', '0006_cityemergencypolicy_normal_first_store_reminder_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityemergencypolicy',
            name='manual_reminder_cooldown_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityemergencypolicy',
            name='manual_reminder_daily_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyfeepolicy',
            name='manual_reminder_cooldown_seconds',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='emergencyfeepolicy',
            name='manual_reminder_daily_limit',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
