# Generated by Django 6.0.7 on 2026-07-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_services', '0007_cityemergencypolicy_manual_reminder_cooldown_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='boundary_mode',
            field=models.CharField(choices=[('radius', 'Automatic radius'), ('manual', 'Advanced manual polygon')], default='radius', max_length=10),
        ),
        migrations.AddField(
            model_name='city',
            name='center_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='center_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='service_radius_km',
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='servicezone',
            name='boundary_mode',
            field=models.CharField(choices=[('radius', 'Automatic radius'), ('manual', 'Advanced manual polygon')], default='radius', max_length=10),
        ),
        migrations.AddField(
            model_name='servicezone',
            name='center_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicezone',
            name='center_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicezone',
            name='service_radius_km',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
