"""
Django settings for aarx project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zm9yafvetr+snvf+*1*0!04)60$sbk-dz3f(kvvlwad1hnh(10'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = [
#     'localhost',
#     '127.0.0.1',
#     '192.168.0.49',
#     '192.168.5.166'
#     '0.0.0.0',
# ]
ALLOWED_HOSTS = ['*']  # Not recommended for production

# for production
# ALLOWED_HOSTS = [
#     'www.yourdomain.com',
#     'yourdomain.com',
#     '123.45.67.89',  # agar IP address se access hota hai to
# ]

# Application definition


INSTALLED_APPS = [
    # 'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'rest_framework',
    'prescription',
    'rest_framework.authtoken',
    'corsheaders',
    'django_celery_results',
    'subscription',




]
# ============================================================
# Celery — Production Scale Configuration
# ============================================================
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
TIME_ZONE = 'UTC'
USE_TZ = True
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Reliability: task acknowledged AFTER completion (not before)
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # 1 task at a time per worker slot

# Concurrency: 4 workers per CPU core for I/O-heavy notification tasks
import multiprocessing
CELERY_WORKER_CONCURRENCY = multiprocessing.cpu_count() * 4

# Task limits
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 120        # hard kill after 2 min
CELERY_TASK_SOFT_TIME_LIMIT = 90    # graceful stop warning at 90s

# Priority queues: fast for direct messages, default for broadcasts
CELERY_TASK_QUEUES = {
    'notifications': {
        'exchange': 'notifications',
        'routing_key': 'notifications',
        'priority': 10,
    },
    'default': {
        'exchange': 'default',
        'routing_key': 'default',
        'priority': 1,
    },
}
CELERY_TASK_DEFAULT_QUEUE = 'default'

# Route all notification tasks to notifications queue
CELERY_TASK_ROUTES = {
    'prescription.tasks.*': {'queue': 'notifications'},
}

REST_FRAMEWORK = {
      'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
      'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # 'DEFAULT_AUTHENTICATION_CLASSES': [],
    # 'DEFAULT_PERMISSION_CLASSES': [],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'TOKEN_EXPIRATION_TIME': None,  # Disable token expiration
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1000/day',
        'user': '5000/hour',
        'location_search': '3/second',
    }
}

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
CORS_ALLOW_ALL_ORIGINS = True  # or CORS_ALLOWED_ORIGINS = ['http://192.168.1.5:19006']

ROOT_URLCONF = 'aarx.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aarx.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'aarxdb',
        'USER': 'aarxuser',
        'PASSWORD': 'aarxpass',
        'HOST': '127.0.0.1',
        'PORT': '6432',
        # ✅ Must be 0 with PgBouncer transaction pool mode.
        'CONN_MAX_AGE': 0,
        # ✅ FIXED: Correct Django setting to disable server-side cursors
        # (incompatible with PgBouncer transaction mode)
        'DISABLE_SERVER_SIDE_CURSORS': True,
    }
}


# Caching Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'max_connections': 100,
            'retry_on_timeout': True,
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Location Service API Keys
# Set GOOGLE_PLACES_API_KEY once billing is enabled in Google Cloud Console.
# Mapbox key is always used as fallback.
GOOGLE_PLACES_API_KEY = None  # Enable billing on Google Cloud to activate
MAPBOX_API_KEY = 'pk.eyJ1IjoicmFodWw4NDk5IiwiYSI6ImNreWZoaGZ5aDE1YWUydXVydmRqYXRidDUifQ.t5UNUnDH9pGxp91_sTMD-A'

# Channels Layer configuration (Redis)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

# Email Backend Configuration (Mailtrap / SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'sandbox.smtp.mailtrap.io')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 2525))
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'webmaster@localhost')

# Meta WhatsApp Cloud API
# Disabled by default so missing/rotated provider credentials can never break
# the existing in-app and email OTP delivery paths.
WHATSAPP_ENABLED = os.getenv('WHATSAPP_ENABLED', 'False').lower() in ('1', 'true', 'yes', 'on')
WHATSAPP_GRAPH_API_VERSION = os.getenv('WHATSAPP_GRAPH_API_VERSION', 'v23.0')
WHATSAPP_PHONE_NUMBER_ID = os.getenv('WHATSAPP_PHONE_NUMBER_ID', '')
WHATSAPP_ACCESS_TOKEN = os.getenv('WHATSAPP_ACCESS_TOKEN', '')
WHATSAPP_TEMPLATE_LANGUAGE = os.getenv('WHATSAPP_TEMPLATE_LANGUAGE', 'en_US')
WHATSAPP_DEFAULT_COUNTRY_CODE = os.getenv('WHATSAPP_DEFAULT_COUNTRY_CODE', '91')
WHATSAPP_PASSWORD_RESET_TEMPLATE = os.getenv(
    'WHATSAPP_PASSWORD_RESET_TEMPLATE',
    'aarx_password_reset_otp',
)
WHATSAPP_COMPLETION_OTP_TEMPLATE = os.getenv(
    'WHATSAPP_COMPLETION_OTP_TEMPLATE',
    'aarx_order_completion_otp',
)
WHATSAPP_OTP_COPY_CODE_BUTTON = os.getenv(
    'WHATSAPP_OTP_COPY_CODE_BUTTON',
    'True',
).lower() in ('1', 'true', 'yes', 'on')

# Razorpay Configuration
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET', '')
RAZORPAY_WEBHOOK_SECRET = os.getenv('RAZORPAY_WEBHOOK_SECRET', '')
