"""
Django settings for aarx project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-local-development-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')
SUPPORT_ATTACHMENT_MALWARE_SCAN_REQUIRED = os.getenv(
    'SUPPORT_ATTACHMENT_MALWARE_SCAN_REQUIRED', 'false' if DEBUG else 'true'
).lower() in ('1', 'true', 'yes', 'on')

# ALLOWED_HOSTS = [
#     'localhost',
#     '127.0.0.1',
#     '192.168.0.49',
#     '192.168.5.166'
#     '0.0.0.0',
# ]
ALLOWED_HOSTS = [host.strip() for host in os.getenv('DJANGO_ALLOWED_HOSTS', '*').split(',') if host.strip()]

# for production
# ALLOWED_HOSTS = [
#     'www.yourdomain.com',
#     'yourdomain.com',
#     '123.45.67.89',  # agar IP address se access hota hai to
# ]

# Application definition


INSTALLED_APPS = [
    # 'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'prescription',
    'rest_framework.authtoken',
    'corsheaders',
    'django_celery_results',
    'subscription',
    'emergency_services',
    'complaints',
    'storages',
    'support_admin',
]
# ============================================================
# Celery — Production Scale Configuration
# ============================================================
CELERY_BROKER_URL = os.getenv('REDIS_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
TIME_ZONE = 'UTC'
USE_TZ = True
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

CELERY_BEAT_SCHEDULE = {
    'support-runtime-heartbeat': {
        'task': 'support_admin.tasks.record_support_runtime_heartbeat',
        'schedule': 30.0,
    },
    'support-due-follow-up-reminders': {
        'task': 'support_admin.tasks.send_due_follow_up_reminders',
        'schedule': 60.0,
    },
    'support-sla-monitor': {
        'task': 'support_admin.tasks.monitor_support_sla_deadlines',
        'schedule': 60.0,
    },
}

# Reliability: task acknowledged AFTER completion (not before)
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # 1 task at a time per worker slot

# Concurrency: 4 workers per CPU core for I/O-heavy notification tasks
import multiprocessing
CELERY_WORKER_CONCURRENCY = multiprocessing.cpu_count() * 4

# Task limits
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 120        # hard kill after 2 min
CELERY_TASK_SOFT_TIME_LIMIT = 90    # graceful stop warning at 90s

# Priority queues: fast for direct messages, default for broadcasts
CELERY_TASK_QUEUES = {
    'notifications': {
        'exchange': 'notifications',
        'routing_key': 'notifications',
        'priority': 10,
    },
    'default': {
        'exchange': 'default',
        'routing_key': 'default',
        'priority': 1,
    },
}
CELERY_TASK_DEFAULT_QUEUE = 'default'

# Route all notification tasks to notifications queue
CELERY_TASK_ROUTES = {
    'prescription.tasks.*': {'queue': 'notifications'},
    'emergency_services.tasks.*': {'queue': 'default'},
}

REST_FRAMEWORK = {
      'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
      'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # 'DEFAULT_AUTHENTICATION_CLASSES': [],
    # 'DEFAULT_PERMISSION_CLASSES': [],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'TOKEN_EXPIRATION_TIME': None,  # Disable token expiration
    'DEFAULT_THROTTLE_CLASSES': [
        'core.throttling.GlobalProjectRateThrottle',
        'core.throttling.EndpointProjectRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'location_search': '3/second',
    }
}

# ============================================================
# Central API Rate Limiting
# Change only these counts/windows to tune the whole app.
# limit = allowed requests during window (seconds)
# ============================================================
API_RATE_LIMITING_ENABLED = os.getenv('API_RATE_LIMITING_ENABLED', 'True').lower() in ('1', 'true', 'yes', 'on')
API_RATE_LIMITS = {
    'global_authenticated_read': {'limit': 600, 'window': 60},
    'global_authenticated_write': {'limit': 120, 'window': 60},
    'global_anonymous_read': {'limit': 120, 'window': 60},
    'global_anonymous_write': {'limit': 30, 'window': 60},
    'login': {'limit': 10, 'window': 300},
    'registration': {'limit': 5, 'window': 3600},
    'otp_request': {'limit': 5, 'window': 600},
    'otp_verify': {'limit': 10, 'window': 600},
    'account_delete': {'limit': 3, 'window': 3600},
    'prescription_upload': {'limit': 12, 'window': 900},
    'media_upload': {'limit': 20, 'window': 600},
    's3_presign': {'limit': 30, 'window': 600},
    'payment_create': {'limit': 10, 'window': 600},
    'payment_verify': {'limit': 15, 'window': 600},
    'provider_webhook': {'limit': 300, 'window': 60},
    'chat_write': {'limit': 60, 'window': 60},
    'report_write': {'limit': 10, 'window': 600},
    'order_action': {'limit': 60, 'window': 60},
    'location_lookup': {'limit': 30, 'window': 60},
    'language_change': {'limit': 20, 'window': 60},
}
API_RATE_LIMIT_RULES = [
    {'pattern': r'^/api/(?:user|store)/login/?$', 'methods': {'POST'}, 'scope': 'login'},
    {'pattern': r'^/api/(?:user|store)/register/?$', 'methods': {'POST'}, 'scope': 'registration'},
    {'pattern': r'^/api/password-reset/request-otp/?$', 'methods': {'POST'}, 'scope': 'otp_request'},
    {'pattern': r'^/api/password-reset/(?:verify-otp|confirm)/?$', 'methods': {'POST'}, 'scope': 'otp_verify'},
    {'pattern': r'^/api/account/delete/?$', 'methods': {'DELETE', 'POST'}, 'scope': 'account_delete'},
    {'pattern': r'^/api/upload/?$', 'methods': {'POST'}, 'scope': 'prescription_upload'},
    {'pattern': r'^/api/chat/.+/(?:upload-audio|upload-media)/?$', 'methods': {'POST'}, 'scope': 'media_upload'},
    {'pattern': r'^/api/s3/(?:presigned-upload|presigned-download)/?$', 'scope': 's3_presign'},
    {'pattern': r'^/api/emergency-service/charges/?$', 'methods': {'POST'}, 'scope': 'payment_create'},
    {'pattern': r'^/api/(?:subscriptions/verify|emergency-service/charges/.+/verify)/?$', 'methods': {'POST'}, 'scope': 'payment_verify'},
    {'pattern': r'^/api/subscriptions/create/?$', 'methods': {'POST'}, 'scope': 'payment_create'},
    {'pattern': r'^/api/(?:subscriptions/webhook|emergency-service/webhooks/razorpay)/?$', 'methods': {'POST'}, 'scope': 'provider_webhook'},
    {'pattern': r'^/api/chat/', 'methods': {'POST', 'PUT', 'PATCH', 'DELETE'}, 'scope': 'chat_write'},
    {'pattern': r'^/api/(?:complaints|safety-reports|store-reports|responses/.+/report)', 'methods': {'POST', 'PUT', 'PATCH'}, 'scope': 'report_write'},
    {'pattern': r'^/api/(?:responses|orders|replacements|store/replacements)/', 'methods': {'POST', 'PUT', 'PATCH', 'DELETE'}, 'scope': 'order_action'},
    {'pattern': r'^/api/(?:search-location|location-details)/?$', 'scope': 'location_lookup'},
    {'pattern': r'^/api/language/?$', 'methods': {'POST', 'PUT', 'PATCH'}, 'scope': 'language_change'},
]
API_RATE_LIMIT_FAIL_CLOSED_SCOPES = {'login', 'registration', 'otp_request', 'otp_verify', 'account_delete', 'payment_create', 'payment_verify'}
NUM_PROXIES = int(os.getenv('API_NUM_PROXIES', '0'))
WEBSOCKET_RATE_LIMITS = {
    'max_connections_per_account': 8,
    'connection_attempts_per_minute': 30,
    'chat_messages_per_minute': 60,
}

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.RateLimitHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'aarx.middleware.ApiResponseTranslationMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
CORS_ALLOW_ALL_ORIGINS = os.getenv(
    'CORS_ALLOW_ALL_ORIGINS', 'true' if DEBUG else 'false'
).lower() == 'true'
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',')
    if origin.strip()
]

# Production security defaults; configure trusted proxy handling explicitly.
SECURE_SSL_REDIRECT = os.getenv(
    'DJANGO_SECURE_SSL_REDIRECT', 'true' if not DEBUG else 'false'
).lower() == 'true'
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'
SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '31536000' if not DEBUG else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
if os.getenv('TRUST_X_FORWARDED_PROTO', 'false').lower() == 'true':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ROOT_URLCONF = 'aarx.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aarx.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.getenv('DB_NAME', 'aarxdb'),
        'USER': os.getenv('DB_USER', 'aarxuser'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'aarxpass'),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '6432'),
        # ✅ Must be 0 with PgBouncer transaction pool mode.
        'CONN_MAX_AGE': 0,
        # ✅ FIXED: Correct Django setting to disable server-side cursors
        # (incompatible with PgBouncer transaction mode)
        'DISABLE_SERVER_SIDE_CURSORS': True,
    }
}


# Caching Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.getenv('REDIS_CACHE_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'max_connections': 100,
            'retry_on_timeout': True,
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('hi', 'Hindi'),
    ('mr', 'Marathi'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Location providers. Mappls is primary; the others are automatic fallbacks.
MAPPLS_CLIENT_ID = os.getenv('MAPPLS_CLIENT_ID') or None
MAPPLS_CLIENT_SECRET = os.getenv('MAPPLS_CLIENT_SECRET') or None
GOOGLE_PLACES_API_KEY = os.getenv('GOOGLE_PLACES_API_KEY') or None
MAPBOX_API_KEY = os.getenv('MAPBOX_API_KEY') or None

# Channels Layer configuration (Redis)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [{
                "address": os.getenv('REDIS_CHANNEL_URL', os.getenv('REDIS_BROKER_URL', 'redis://127.0.0.1:6379/0')),
                "socket_connect_timeout": 5,
                "socket_timeout": 15,
                "retry_on_timeout": True,
                "health_check_interval": 30,
            }],
        },
    },
}

# Email Backend Configuration (Mailtrap / SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'sandbox.smtp.mailtrap.io')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 2525))
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'webmaster@localhost')

# Meta WhatsApp Cloud API
# Disabled by default so missing/rotated provider credentials can never break
# the existing in-app and email OTP delivery paths.
WHATSAPP_ENABLED = os.getenv('WHATSAPP_ENABLED', 'False').lower() in ('1', 'true', 'yes', 'on')
WHATSAPP_GRAPH_API_VERSION = os.getenv('WHATSAPP_GRAPH_API_VERSION', 'v23.0')
WHATSAPP_PHONE_NUMBER_ID = os.getenv('WHATSAPP_PHONE_NUMBER_ID', '')
WHATSAPP_ACCESS_TOKEN = os.getenv('WHATSAPP_ACCESS_TOKEN', '')
WHATSAPP_TEMPLATE_LANGUAGE = os.getenv('WHATSAPP_TEMPLATE_LANGUAGE', 'en_US')
WHATSAPP_DEFAULT_COUNTRY_CODE = os.getenv('WHATSAPP_DEFAULT_COUNTRY_CODE', '91')
WHATSAPP_PASSWORD_RESET_TEMPLATE = os.getenv(
    'WHATSAPP_PASSWORD_RESET_TEMPLATE',
    'aarx_password_reset_otp',
)
WHATSAPP_COMPLETION_OTP_TEMPLATE = os.getenv(
    'WHATSAPP_COMPLETION_OTP_TEMPLATE',
    'aarx_order_completion_otp',
)
WHATSAPP_OTP_COPY_CODE_BUTTON = os.getenv(
    'WHATSAPP_OTP_COPY_CODE_BUTTON',
    'True',
).lower() in ('1', 'true', 'yes', 'on')

# Razorpay Configuration
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET', '')
RAZORPAY_WEBHOOK_SECRET = os.getenv('RAZORPAY_WEBHOOK_SECRET', '')
EMERGENCY_RAZORPAY_WEBHOOK_SECRET = os.getenv('EMERGENCY_RAZORPAY_WEBHOOK_SECRET', RAZORPAY_WEBHOOK_SECRET)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# AWS S3 Storage — Production File Storage
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', 'aarx-media')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'eu-north-1')
AWS_S3_ADDRESSING_STYLE = os.getenv('AWS_S3_ADDRESSING_STYLE', 'virtual')
AWS_S3_PRESIGNED_URL_EXPIRY = int(os.getenv('AWS_S3_PRESIGNED_URL_EXPIRY', 3600))

# Enable S3 storage only when AWS credentials are configured
_s3_enabled = bool(AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY)

if _s3_enabled:
    # Use S3 as default file storage for all ImageField/FileField
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

    # S3 Bucket Settings
    AWS_S3_FILE_OVERWRITE = False          # Don't overwrite files with same name
    AWS_DEFAULT_ACL = None                 # Private by default (presigned URLs for access)
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',   # 1 day cache
    }
    AWS_QUERYSTRING_AUTH = True             # Use presigned URLs (private bucket)
    AWS_QUERYSTRING_EXPIRE = AWS_S3_PRESIGNED_URL_EXPIRY
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_CUSTOM_DOMAIN = None            # No custom domain, use presigned URLs
    AWS_S3_ADDRESSING_STYLE = 'virtual'    # Virtual-hosted style URLs
