import { LocalizedText as Text, LocalizedTextInput as TextInput } from '@/components/Language/LocalizedPrimitives';
import React,{useCallback,useEffect,useState}from'react';
import {
  ActivityIndicator,
  Alert,
  FlatList,
  Image,
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  TouchableOpacity,
  View
} from 'react-native';
import{MaterialCommunityIcons}from'@expo/vector-icons';
import{useIsFocused}from'@react-navigation/native';
import{useLocalSearchParams,useRouter}from'expo-router';
import*as ImagePicker from'expo-image-picker';
import{SUPPORT_CATEGORIES,createSupportTicket,getSupportTicket,getSupportTickets,replySupportTicket,type SupportTicket}from'@/utils/platformSupportApi';
const color=(s:string)=>s==='resolved'||s==='closed'?'#059669':s==='waiting_for_user'?'#d97706':'#2563eb';
function Header({title,subtitle}:{title:string;subtitle:string}){const r=useRouter();return <View className="bg-slate-950 px-5 pt-5 pb-6"><TouchableOpacity onPress={()=>r.back()} className="mb-5"><MaterialCommunityIcons name="arrow-left" size={24} color="white"/></TouchableOpacity><Text className="text-white text-2xl font-black">{title}</Text><Text className="text-slate-400 text-xs leading-5 mt-2">{subtitle}</Text></View>}
export function SupportTicketList(){const r=useRouter(),focused=useIsFocused();const[data,setData]=useState<SupportTicket[]>([]),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(false);const load=useCallback(async()=>{try{setData(await getSupportTickets())}catch{Alert.alert('Could not load','Please check your connection and try again.')}finally{setLoading(false);setRefresh(false)}},[]);useEffect(()=>{focused&&load()},[focused,load]);return <View className="flex-1 bg-slate-50"><Header title="AARX Support" subtitle="For app bugs, account, verification, subscription and technical issues. This is separate from complaints against users or pharmacies."/><TouchableOpacity onPress={()=>r.push('/platform-support/raise')} className="m-4 bg-emerald-600 rounded-2xl p-4 flex-row items-center"><MaterialCommunityIcons name="message-plus-outline" size={24} color="white"/><View className="ml-3 flex-1"><Text className="text-white font-black">New support request</Text><Text className="text-emerald-100 text-xs mt-1">Tell the AARX team what went wrong</Text></View><MaterialCommunityIcons name="chevron-right" size={23} color="white"/></TouchableOpacity>{loading?<ActivityIndicator className="mt-12" color="#059669"/>:<FlatList data={data} refreshing={refresh} onRefresh={()=>{setRefresh(true);load()}} keyExtractor={x=>String(x.id)} contentContainerStyle={{paddingHorizontal:16,paddingBottom:40}} ListEmptyComponent={<View className="items-center py-16"><MaterialCommunityIcons name="check-decagram-outline" size={42} color="#94a3b8"/><Text className="font-bold text-slate-700 mt-4">No support requests yet</Text></View>} renderItem={({item})=><TouchableOpacity onPress={()=>r.push(`/platform-support/${item.id}`)} className="bg-white border border-slate-200 rounded-2xl p-4 mb-3"><View className="flex-row items-center"><Text className="text-slate-400 text-[10px] font-bold">#{item.id} · {item.category_display}</Text><View style={{backgroundColor:color(item.status)+'18'}} className="ml-auto rounded-full px-2.5 py-1"><Text style={{color:color(item.status)}} className="text-[10px] font-black">{item.status_display}</Text></View></View><Text className="font-black text-slate-950 text-[15px] mt-3">{item.subject}</Text><Text className="text-slate-400 text-[11px] mt-2">{item.message_count} replies{item.unread_count?` · ${item.unread_count} unread`:''}</Text></TouchableOpacity>}/>}</View>}
export function RaiseSupportTicket(){const r=useRouter();const[category,setCategory]=useState('technical'),[subject,setSubject]=useState(''),[description,setDescription]=useState(''),[priority,setPriority]=useState('medium'),[image,setImage]=useState<{uri:string;name:string;type:string}|null>(null),[saving,setSaving]=useState(false);const pick=async()=>{const x=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.7});if(!x.canceled){const a=x.assets[0];setImage({uri:a.uri,name:a.fileName||'support.jpg',type:a.mimeType||'image/jpeg'})}};const submit=async()=>{if(subject.trim().length<4||description.trim().length<10)return Alert.alert('More details needed','Add a clear subject and description.');try{setSaving(true);const t=await createSupportTicket({category,subject:subject.trim(),description:description.trim(),priority},image);r.replace(`/platform-support/${t.id}`)}catch(e){Alert.alert('Could not submit',e instanceof Error?e.message:'Please try again.')}finally{setSaving(false)}};return <ScrollView className="flex-1 bg-slate-50" keyboardShouldPersistTaps="handled"><Header title="Contact AARX Support" subtitle="Do not use this for a dispute with a user or pharmacy. Raise a complaint for those cases."/><View className="p-4"><Text className="font-black text-slate-800 mb-3">Issue type</Text><View className="flex-row flex-wrap">{SUPPORT_CATEGORIES.map(x=><TouchableOpacity key={x.value} onPress={()=>setCategory(x.value)} className={`mr-2 mb-2 px-3 py-2 rounded-xl border ${category===x.value?'bg-emerald-50 border-emerald-600':'bg-white border-slate-200'}`}><Text className={category===x.value?'text-emerald-700 font-bold':'text-slate-600'}>{x.label}</Text></TouchableOpacity>)}</View><Text className="font-black text-slate-800 mt-4 mb-2">Subject</Text><TextInput value={subject} onChangeText={setSubject} maxLength={200} placeholder="Short summary of the problem" className="bg-white border border-slate-200 rounded-2xl px-4 py-4"/><Text className="font-black text-slate-800 mt-4 mb-2">What happened?</Text><TextInput value={description} onChangeText={setDescription} multiline textAlignVertical="top" placeholder="Include steps, error messages and what you expected" className="bg-white border border-slate-200 rounded-2xl px-4 py-4 min-h-[150px]"/><TouchableOpacity onPress={pick} className="mt-4 bg-white border border-slate-200 rounded-2xl p-4 flex-row items-center"><MaterialCommunityIcons name="paperclip" size={21} color="#475569"/><Text className="ml-3 font-bold text-slate-700">{image?'Screenshot attached':'Attach screenshot (optional)'}</Text></TouchableOpacity><TouchableOpacity disabled={saving} onPress={submit} className="mt-5 mb-10 bg-emerald-600 rounded-2xl py-4 items-center">{saving?<ActivityIndicator color="white"/>:<Text className="text-white font-black">Submit support request</Text>}</TouchableOpacity></View></ScrollView>}
export function SupportTicketDetail(){const{id}=useLocalSearchParams<{id:string}>();const[t,setT]=useState<SupportTicket|null>(null),[text,setText]=useState(''),[sending,setSending]=useState(false);const load=useCallback(async()=>{try{setT(await getSupportTicket(Number(id)))}catch{Alert.alert('Not found','This support request could not be loaded.')}},[id]);useEffect(()=>{load()},[load]);const send=async()=>{if(!text.trim())return;try{setSending(true);setT(await replySupportTicket(Number(id),text.trim()));setText('')}catch(e){Alert.alert('Could not send',e instanceof Error?e.message:'Try again.')}finally{setSending(false)}};if(!t)return <View className="flex-1 items-center justify-center"><ActivityIndicator color="#059669"/></View>;return <KeyboardAvoidingView className="flex-1 bg-slate-50" behavior={Platform.OS==='ios'?'padding':undefined}><Header title={`Support #${t.id}`} subtitle={t.category_display}/><ScrollView className="flex-1 p-4"><View className="bg-white border border-slate-200 rounded-2xl p-4"><View className="flex-row"><Text style={{color:color(t.status)}} className="font-black text-xs">{t.status_display}</Text><Text className="ml-auto text-slate-400 text-xs">{t.priority_display}</Text></View><Text className="text-slate-950 font-black text-lg mt-3">{t.subject}</Text><Text className="text-slate-600 leading-5 mt-3">{t.description}</Text>{t.resolution_note?<View className="bg-emerald-50 rounded-xl p-3 mt-4"><Text className="text-emerald-900 font-bold">Resolution</Text><Text className="text-emerald-800 mt-1">{t.resolution_note}</Text></View>:null}</View><Text className="text-slate-400 font-black text-[10px] tracking-widest mt-6 mb-3">CONVERSATION</Text>{(t.messages||[]).map(m=><View key={m.id} className={`rounded-2xl p-4 mb-3 ${m.sender_type==='platform'?'bg-white border border-slate-200 self-start':'bg-emerald-600 self-end'}`}><Text className={`text-[10px] font-black mb-2 ${m.sender_type==='platform'?'text-emerald-700':'text-emerald-100'}`}>{m.sender_name}</Text>{m.text?<Text className={m.sender_type==='platform'?'text-slate-700':'text-white'}>{m.text}</Text>:null}{m.attachment?<Image source={{uri:m.attachment}} className="w-48 h-36 rounded-xl mt-2"/>:null}</View>)}</ScrollView>{t.status!=='closed'?<View className="bg-white border-t border-slate-200 p-3 flex-row items-end"><TextInput value={text} onChangeText={setText} multiline placeholder="Reply to AARX Support" className="flex-1 bg-slate-100 rounded-2xl px-4 py-3 max-h-28"/><TouchableOpacity disabled={sending} onPress={send} className="bg-emerald-600 w-12 h-12 ml-2 rounded-2xl items-center justify-center">{sending?<ActivityIndicator color="white"/>:<MaterialCommunityIcons name="send" size={20} color="white"/>}</TouchableOpacity></View>:null}</KeyboardAvoidingView>}