# Generated by Django 5.2.6 on 2026-07-10 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescription', '0093_appnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('razorpay_plan_id', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_subscription_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('authenticated', 'Authenticated'), ('active', 'Active'), ('pending', 'Pending'), ('halted', 'Halted'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('expired', 'Expired')], default='created', max_length=20)),
                ('current_start', models.IntegerField(blank=True, null=True)),
                ('current_end', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.plan')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='prescription.store')),
            ],
        ),
    ]
