# Generated by Django 6.0.7 on 2026-07-14 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0093_appnotification'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of feature strings'),
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='prescription.store')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscription.storesubscription')),
            ],
        ),
    ]
