import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import toast from 'react-hot-toast'
import { AlertTriangle, GitBranch, RotateCcw, ShieldCheck, Wrench, RefreshCw } from 'lucide-react'
import { caseManagementApi, type CaseType } from '@/api/caseManagementApi'
import { Button } from '@/components/common/Button'
import { useCurrentUser } from '@/store/authStore'

type Props = { entityType: CaseType; objectId: string | number; status: string; subject: string }
type Mode = 'escalate' | 'link' | 'merge' | 'engineering' | 'sensitive' | null

const SIMPLE_LABELS: Record<string, string> = {
  supervisor: 'Senior support staff', technical: 'Technical team', emergency: 'Emergency response team', legal: 'Legal and compliance team',
  open: 'Waiting', accepted: 'Team is working on it', resolved: 'Help completed', cancelled: 'Cancelled', pending: 'Waiting for approval', approved: 'Approved', rejected: 'Rejected',
  related: 'Related problem', duplicate: 'Reported twice', caused_by: 'Caused by', complaint: 'Complaint', ticket: 'Help request', refund: 'Refund request', safety_report: 'Safety issue',
  account_suspend: 'Block an account', account_restore: 'Restore a blocked account', personal_data_change: 'Change personal information', high_value_refund: 'High-value refund',
  low: 'Low importance', medium: 'Normal importance', high: 'High importance', urgent: 'Urgent',
}
const simpleLabel = (value: string) => SIMPLE_LABELS[value] || value.replace(/_/g, ' ')

export const CaseManagementPanel = ({ entityType, objectId, status, subject }: Props) => {
  const user = useCurrentUser()
  const senior = user?.role === 'admin' || user?.role === 'supervisor'
  const queryClient = useQueryClient()
  const [mode, setMode] = useState<Mode>(null)
  const [form, setForm] = useState<Record<string, string>>({})
  const queryKey = ['case-management', entityType, String(objectId)]
  const query = useQuery({ queryKey, queryFn: () => caseManagementApi.get(entityType, objectId), staleTime: 10_000 })
  const mutation = useMutation({
    mutationFn: (payload: Record<string, unknown>) => caseManagementApi.act(entityType, objectId, payload),
    onSuccess: async () => { setMode(null); setForm({}); await queryClient.invalidateQueries({ queryKey }); toast.success('Case information saved') },
    onError: () => toast.error('Could not save this change'),
  })
  const data = query.data
  const submit = (action: string) => mutation.mutate({ action, ...form })
  const terminal = ['resolved', 'closed', 'rejected', 'withdrawn'].includes(status)

  return <section className="rounded-2xl border border-slate-200 bg-white shadow-sm">
    <div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold text-slate-900">Need more help with this case?</h2><p className="text-xs text-slate-500">Send it to another team, connect a similar case, or ask a senior staff member for approval.</p></div>
    <div className="space-y-4 p-5">
      <div className="grid grid-cols-2 gap-2">
        <Action icon={<AlertTriangle />} label="Send to another team" hint="Use when a supervisor, technical, emergency, or legal team is needed." onClick={() => setMode('escalate')} />
        <Action icon={<GitBranch />} label="Connect another case" hint="Use when another case is about the same customer problem." onClick={() => setMode('link')} />
        <Action icon={<Wrench />} label="Report a technical problem" hint="Send an app, server, or payment-system problem to the technical team." onClick={() => setMode('engineering')} />
        <Action icon={<ShieldCheck />} label="Request approval" hint="Required before account, personal-data, or high-value refund actions." onClick={() => setMode('sensitive')} />
        {senior && ['complaint', 'ticket'].includes(entityType) && <Action icon={<GitBranch />} label="Merge a duplicate case" hint="Close a second report of the same problem and keep this case as the main case." onClick={() => setMode('merge')} />}
      </div>
      {senior && terminal && <Button className="w-full" variant="secondary" onClick={() => { const reason = window.prompt('Why does this completed case need more work?'); if (reason?.trim()) mutation.mutate({ action: 'reopen', reason }) }}><RotateCcw className="mr-2 h-4 w-4" />Open this completed case again</Button>}
      {mode === 'escalate' && <Form title="Send this case to another team" help="Choose the team, explain why their help is needed, and tell them what to do next."><Select value={form.destination} onChange={value => setForm({ ...form, destination: value })} options={[['supervisor','Senior support staff'],['technical','Technical team'],['emergency','Emergency response team'],['legal','Legal and compliance team']]} /><Text placeholder="Why does this case need another team?" value={form.reason} onChange={reason => setForm({ ...form, reason })} /><Text placeholder="What should the next team know and do?" value={form.handover_note} onChange={handover_note => setForm({ ...form, handover_note })} /><Submit onCancel={() => setMode(null)} onSubmit={() => submit('escalate')} disabled={!form.destination || !form.reason?.trim() || !form.handover_note?.trim()} loading={mutation.isPending} /></Form>}
      {mode === 'link' && <Form title="Connect another case" help="Connect cases about the same customer, order, payment, or problem."><Select value={form.target_type} onChange={target_type => setForm({ ...form, target_type })} options={[['complaint','Customer complaint'],['ticket','Help request'],['refund','Refund request'],['safety_report','Safety issue']]} /><input className="input" type="number" min="1" placeholder="Enter the other case number" value={form.target_id || ''} onChange={e => setForm({ ...form, target_id: e.target.value })} /><Select value={form.relation} onChange={relation => setForm({ ...form, relation })} options={[['related','Same or related problem'],['duplicate','Same case reported twice'],['caused_by','This case was caused by the other case']]} /><Text placeholder="How are these cases connected?" value={form.reason} onChange={reason => setForm({ ...form, reason })} /><Submit onCancel={() => setMode(null)} onSubmit={() => submit('link')} disabled={!form.target_type || !form.target_id} loading={mutation.isPending} /></Form>}
      {mode === 'merge' && <Form title="Merge a duplicate into this case" help="This case will stay open as the main case. The duplicate will close, but its messages and history will not be deleted."><input className="input" type="number" min="1" placeholder={`Duplicate ${entityType === 'complaint' ? 'complaint' : 'help request'} number`} value={form.duplicate_id || ''} onChange={e => setForm({ ...form, duplicate_id: e.target.value })} /><Text placeholder="Why are these two cases duplicates?" value={form.reason} onChange={reason => setForm({ ...form, reason })} /><Submit onCancel={() => setMode(null)} onSubmit={() => { if (window.confirm('Close the duplicate case and keep this case as the main case?')) submit('merge_duplicate') }} disabled={!form.duplicate_id || !form.reason?.trim()} loading={mutation.isPending} /></Form>}
      {mode === 'engineering' && <Form title="Report a problem to the technical team" help="Include enough detail for the technical team to find and fix the problem."><input className="input" placeholder="Short name for the problem" value={form.title || subject} onChange={e => setForm({ ...form, title: e.target.value })} /><Text placeholder="What happened? Include steps, error message, and expected result." value={form.description} onChange={description => setForm({ ...form, description })} /><Select value={form.priority} onChange={priority => setForm({ ...form, priority })} options={[['low','Low — can wait'],['medium','Normal'],['high','High — customer work affected'],['urgent','Urgent — service or payment blocked']]} /><input className="input" placeholder="Technical owner or team (optional)" value={form.owner || ''} onChange={e => setForm({ ...form, owner: e.target.value })} /><Submit onCancel={() => setMode(null)} onSubmit={() => mutation.mutate({ action: 'engineering_handoff', title: form.title || subject, ...form })} disabled={!(form.title || subject).trim() || !form.description?.trim()} loading={mutation.isPending} /></Form>}
      {mode === 'sensitive' && <Form title="Ask a senior staff member for approval" help="Customer verification proof is required before this protected action can be approved."><Select value={form.action_type} onChange={action_type => setForm({ ...form, action_type })} options={[['account_suspend','Block an account'],['account_restore','Restore a blocked account'],['personal_data_change','Change personal information'],['high_value_refund','Approve a high-value refund']]} /><Text placeholder="Why is this protected action needed?" value={form.reason} onChange={reason => setForm({ ...form, reason })} /><input className="input" placeholder="How was the customer verified? Example: OTP, call, document" value={form.verification_method || ''} onChange={e => setForm({ ...form, verification_method: e.target.value })} /><input className="input" placeholder="Verification proof or reference number" value={form.verification_reference || ''} onChange={e => setForm({ ...form, verification_reference: e.target.value })} /><Submit onCancel={() => setMode(null)} onSubmit={() => submit('sensitive_action')} disabled={!form.action_type || !form.reason?.trim() || !form.verification_method?.trim() || !form.verification_reference?.trim()} loading={mutation.isPending} /></Form>}
      {!!data?.escalations.length && <div><p className="mb-2 text-xs font-semibold uppercase text-slate-500">Cases sent to another team</p>{data.escalations.map(item => <div key={item.id} className="mb-2 rounded-lg bg-slate-50 p-2 text-xs"><p>{simpleLabel(item.destination)} · {simpleLabel(item.status)} · {item.reason}</p>{senior && !['resolved','cancelled'].includes(item.status) && <div className="mt-2 flex gap-2"><Button size="sm" variant="ghost" onClick={() => mutation.mutate({ action: 'update_escalation', escalation_id: item.id, status: 'accepted' })}>Take responsibility</Button><Button size="sm" variant="ghost" onClick={() => mutation.mutate({ action: 'update_escalation', escalation_id: item.id, status: 'resolved' })}>Mark help completed</Button></div>}</div>)}</div>}
      {!!data?.relations.length && <List title="Connected cases" items={data.relations.map(item => `${simpleLabel(item.relation)}: ${simpleLabel(item.source_type)} #${item.source_id} ↔ ${simpleLabel(item.target_type)} #${item.target_id}`)} />}
      {!!data?.engineering_issues.length && <div><p className="mb-2 text-xs font-semibold uppercase text-slate-500">Technical team work</p>{data.engineering_issues.map(item => <div key={item.id} className="mb-2 flex items-center gap-2 rounded-lg bg-slate-50 p-2 text-xs"><span className="min-w-0 flex-1 truncate">{item.title} · {item.priority}{item.owner ? ` · ${item.owner}` : ''}</span><select aria-label="Technical work progress" className="rounded border border-slate-200 bg-white p-1" value={item.status} onChange={e => mutation.mutate({ action: 'update_engineering', issue_id: item.id, status: e.target.value })}><option value="open">Waiting for technical team</option><option value="triaged">Problem checked</option><option value="in_progress">Fix in progress</option><option value="fixed">Fix completed</option><option value="closed">Work closed</option></select></div>)}</div>}
      {!!data?.sensitive_actions.length && <div><p className="mb-2 text-xs font-semibold uppercase text-slate-500">Actions waiting for senior approval</p>{data.sensitive_actions.map(item => <div key={item.id} className="mb-2 rounded-lg bg-slate-50 p-3 text-xs"><p className="font-medium">{item.action_type.replace(/_/g, ' ')} · {item.status}</p><p className="text-slate-500">Customer checked using: {item.verification_method}</p>{senior && item.status === 'pending' && <div className="mt-2 flex gap-2"><Button size="sm" onClick={() => mutation.mutate({ action: 'approve_sensitive', request_id: item.id })}>Approve this request</Button><Button size="sm" variant="secondary" onClick={() => mutation.mutate({ action: 'reject_sensitive', request_id: item.id })}>Reject this request</Button></div>}</div>)}</div>}
      {!!data?.deliveries.length && <div><p className="mb-2 text-xs font-semibold uppercase text-slate-500">Did the customer receive the message?</p>{data.deliveries.map(item => <div key={item.id} className="flex items-center gap-2 rounded-lg bg-slate-50 p-2 text-xs"><span className="flex-1">{item.title} · {item.status} · tried {item.attempts} time(s)</span>{item.status !== 'delivered' && <Button title="Try sending this notification again" size="sm" variant="ghost" onClick={() => mutation.mutate({ action: 'retry_delivery', notification_id: item.id })}><RefreshCw className="h-3.5 w-3.5" /></Button>}</div>)}</div>}
    </div>
  </section>
}

const Action = ({ icon, label, hint, onClick }: { icon: React.ReactNode; label: string; hint: string; onClick: () => void }) => <button onClick={onClick} title={hint} className="rounded-lg border border-slate-200 p-2.5 text-left hover:bg-slate-50"><span className="flex items-center gap-2 text-xs font-semibold">{icon}{label}</span><span className="mt-1 block text-[11px] leading-4 text-slate-500">{hint}</span></button>
const Form = ({ title, help, children }: { title: string; help?: string; children: React.ReactNode }) => <div className="space-y-2 rounded-xl border border-primary-100 bg-primary-50/40 p-3"><p className="text-sm font-semibold">{title}</p>{help && <p className="text-xs leading-5 text-slate-600">{help}</p>}{children}</div>
const Text = ({ placeholder, value, onChange }: { placeholder: string; value?: string; onChange: (value: string) => void }) => <textarea className="input min-h-20" placeholder={placeholder} value={value || ''} onChange={e => onChange(e.target.value)} />
const Select = ({ value, onChange, options }: { value?: string; onChange: (value: string) => void; options: string[][] }) => <select className="input" value={value || ''} onChange={e => onChange(e.target.value)}><option value="">Choose…</option>{options.map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select>
const Submit = ({ onCancel, onSubmit, disabled, loading }: { onCancel: () => void; onSubmit: () => void; disabled: boolean; loading: boolean }) => <div className="flex justify-end gap-2"><Button size="sm" variant="ghost" onClick={onCancel}>Cancel</Button><Button size="sm" disabled={disabled} loading={loading} onClick={onSubmit}>Save</Button></div>
const List = ({ title, items }: { title: string; items: string[] }) => <div><p className="mb-2 text-xs font-semibold uppercase text-slate-500">{title}</p><div className="space-y-1">{items.map((item,index) => <p key={`${item}-${index}`} className="rounded-lg bg-slate-50 p-2 text-xs text-slate-700">{item}</p>)}</div></div>
