import axios from'axios';import Constants from'expo-constants';import*as SecureStore from'expo-secure-store';
const B=(Constants.expoConfig?.extra?.BASE_URL as string)||'';
export const PHARMACIST_CATEGORIES=[{value:'how_to_take',label:'How and when to take'},{value:'food_timing',label:'Before or after food'},{value:'missed_dose',label:'Missed dose'},{value:'side_effects',label:'Common side effects'},{value:'storage',label:'Storage'},{value:'prescription_help',label:'Understand prescription'},{value:'other',label:'Other'}];
export type Consultation={id:number;order_id:number;category:string;category_display:string;medicine_name:string;question:string;status:string;status_display:string;callback_requested:boolean;callback_phone:string;callback_preferred_time:string;pharmacy_name:string;pharmacy_phone:string;pharmacist_name:string;pharmacist_verified:boolean;pharmacist_available:boolean;created_at:string;updated_at:string;order_context?:{id:number;status:string;delivery_option:string|null;distance_km:string|null;customer_name:string;customer_mobile:string;customer_address:string|null;prescription_image_url:string|null;prescription_medicine_name:string|null;prescription_description:string|null;response_text:string|null;total_amount:string|null;created_at:string;completed_at:string|null;medicines:{name:string;brand:string|null;type:string;price:string|null;is_available:boolean}[];timeline:{from_status:string;to_status:string;reason:string|null;changed_by:string|null;created_at:string}[]};messages:{id:number;sender_type:'user'|'pharmacist';text:string;attachment:string|null;pharmacist_name:string;created_at:string}[]};
async function h(){return{Authorization:`Bearer ${await SecureStore.getItemAsync('authToken')||''}`}}
export async function getOrderConsultation(orderId:number){return(await axios.get(B+`/api/pharmacist/order/${orderId}/`,{headers:await h()})).data as{eligible:boolean;reason:string;pharmacy_name:string;pharmacy_phone:string;pharmacist_verified:boolean;pharmacist_available:boolean;consultation:Consultation|null}}
export async function createConsultation(orderId:number,v:{category:string;medicine_name:string;question:string;consent:boolean}){const f=new FormData();Object.entries(v).forEach(([k,x])=>f.append(k,String(x)));const r=await fetch(B+`/api/pharmacist/order/${orderId}/`,{method:'POST',headers:await h(),body:f});if(!r.ok)throw new Error(await errorText(r));return r.json() as Promise<Consultation>}
export async function getConsultation(id:number){return(await axios.get(B+`/api/pharmacist/consultations/${id}/`,{headers:await h()})).data as Consultation}
export async function sendConsultationMessage(id:number,text:string){const f=new FormData();f.append('text',text);const r=await fetch(B+`/api/pharmacist/consultations/${id}/`,{method:'POST',headers:await h(),body:f});if(!r.ok)throw new Error(await errorText(r));return r.json() as Promise<Consultation>}
export async function requestPharmacistCallback(id:number,phone:string,preferred_time:string){return(await axios.post(B+`/api/pharmacist/consultations/${id}/callback/`,{phone,preferred_time},{headers:await h()})).data as Consultation}
export async function getStoreConsultations(){return(await axios.get(B+'/api/pharmacist/store/inbox/',{headers:await h()})).data as Consultation[]}
export async function getPharmacistAvailability(){return(await axios.get(B+'/api/pharmacist/store/availability/',{headers:await h()})).data as{pharmacist_name:string;license_number:string;verified:boolean;available:boolean}}
export async function setPharmacistAvailability(available:boolean){return(await axios.patch(B+'/api/pharmacist/store/availability/',{available},{headers:await h()})).data}
async function errorText(r:Response){try{const x=await r.json();return x.error||Object.values(x).flat().join(' ')||'Request failed.'}catch{return'Request failed.'}}
export async function submitPharmacistDetails(pharmacist_name:string,license_number:string){return(await axios.patch(B+'/api/pharmacist/store/availability/',{pharmacist_name,license_number},{headers:await h()})).data}
